use std::{process::ExitCode};

use crate::io::DcIoUDP;

use clap::{Parser, Subcommand};
use clap_num::maybe_hex;

#[macro_use]
extern crate log;

mod cmds;
mod cd;
mod fs;
mod disc_formats;
mod dispatch;
mod io;
mod loaders;
mod memmap;
mod presets;
mod types;
mod ui;

const PROTOCOL_VERSION_LEGACY: [u8; 3] = [0, 0, 0];
const PROTOCOL_VERSION_MODERN: [u8; 3] = [2, 0, 3];
// Keep this easy to toggle. 1024 => legacy mode, 1440 => modern mode.
const CHUNK_SIZE: usize = 1440;

pub(crate) fn protocol_version() -> [u8; 3] {
    if CHUNK_SIZE <= 1024 {
        PROTOCOL_VERSION_LEGACY
    } else {
        PROTOCOL_VERSION_MODERN
    }
}

// Simple program to greet a person
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// Verbosity level (-v, -vv)
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: Option<u8>,

    /// UDP port to connect to
    #[arg(short, long, default_value_t = 53535)]
    port: u16,

    /// Host to connect to
    #[arg(short = 'H', long, default_value = "", value_hint = clap::ValueHint::Hostname)]
    host: String,

    /// Address to execute code at
    #[arg(short, long, default_value_t = 0x0c010000, default_value = "0x0c010000", value_parser = maybe_hex::<u32>)]
    address: u32,

    /// Directory of per-base dcload ELFs (dcload-0x8cfe8000.elf, ...).
    /// Defaults to $DCLOAD_LOADER_DIR, else `loaders/` in this project's root
    /// -- the same place for a debug build, a release build and `cargo run`,
    /// and outside `target/` so `cargo clean` leaves it alone. A `loaders`
    /// directory next to the executable is still honoured, last.
    /// Build the set with `make -C target-src/dcload loaders`.
    #[arg(long, value_hint = clap::ValueHint::DirPath)]
    loader_dir: Option<String>,

    /// Per-game settings table (game-presets.tsv, generated by dcload-ip's
    /// scripts/make-preset-db.py from DreamShell's isoldr presets).
    /// Defaults to $DCLOAD_GAME_DB, else game-presets.tsv beside the loaders,
    /// else in this project's root -- outside `target/`, and the same file for
    /// a debug build and a release build.
    #[arg(long, value_hint = clap::ValueHint::FilePath)]
    game_db: Option<String>,

    /// Link the loader at this address instead of asking the database.
    /// `--loader-base 0x8c004000` pins the stock base; use it to check whether
    /// a relocation is what changed a title's behaviour.
    #[arg(long, value_parser = maybe_hex::<u32>)]
    loader_base: Option<u32>,

    /// Never chainload: run whatever loader is already on the console.
    #[arg(long)]
    no_relocate: bool,

    /// Poke a 32-bit word into RAM after the title is uploaded and just before
    /// it runs: `--patch 0x8c0c0d6c=0x0009000b` (that word is `rts; nop`, i.e.
    /// "make this routine do nothing"). Repeatable. The address may be given in
    /// either window. Same mechanism as DreamShell's per-game pa1/pv1 fields --
    /// and, when a title hangs before its first disc read, the only instrument
    /// left: nothing else on the console can be read back at that point.
    #[arg(long, value_parser = parse_patch)]
    patch: Vec<(u32, u32)>,

    /// Do not neutralise a title's GAPS-bridge probe.
    ///
    /// By default the host looks in the uploaded image for the signature a
    /// Katana title uses to find an expansion device, and blunts it, because a
    /// title that finds the Broadband Adapter switches it OFF -- see
    /// AGENTS.md 4.12. Pass this to leave the title exactly as shipped and let
    /// dcload's own recovery handle it.
    #[arg(long)]
    no_gaps_guard: bool,

    /// Place a "phone home" probe at ADDR that reports through dcload's own
    /// syscall trampoline: `--probe 0x8c110bec=37` makes the console log
    /// `Write(1, .., 37)` the moment that address is executed. ID is 1..127
    /// and only names the probe. Repeatable.
    ///
    /// Prefer this to a `trapa` patch once a title has started: a title takes
    /// over the exception vectors during its own start-up, and from then on
    /// "the probe fired" and "the probe was never reached" are the same dead
    /// console. This path belongs to the loader, needs no vector table, and
    /// says so in the log. The stub destroys 28 bytes at ADDR and parks there.
    /// Where to read and write the learned memory map (game-memory.tsv)
    #[arg(long, value_hint = clap::ValueHint::FilePath)]
    memory_db: Option<String>,

    #[arg(long, value_parser = parse_probe)]
    probe: Vec<(u32, u8, Option<u32>)>,

    /// What to do about a SCRAMBLED boot binary.
    ///
    /// A binary meant to boot from a CD-R is stored with its 32-byte slices
    /// permuted, and the disc's own bootstrap unpermutes it while loading. This
    /// host never runs that bootstrap -- it enters the binary directly, as
    /// isoldr does -- so a scrambled one has to be undone here or what runs is
    /// noise. A `.gdi` dumped from a GD-ROM is never scrambled; a `.cdi`
    /// self-boot conversion usually is.
    ///
    /// `auto` (the default) undoes it only when it can be PROVEN, which is
    /// possible for homebrew and not for retail titles -- see
    /// `disc_formats::scramble`. If a title uploads cleanly and then does
    /// absolutely nothing, `--descramble always` is the next thing to try.
    #[arg(long, value_enum, default_value_t = DescrambleArg::Auto)]
    descramble: DescrambleArg,

    /// Enter the title through its own IP.BIN bootstrap instead of jumping
    /// straight into 1ST_READ.BIN -- what isoldr does for every preset with
    /// `fastboot = 0`, which includes Sonic Adventure 2.
    ///
    /// Loads all sixteen IP.BIN sectors to 0x8c008000, applies isoldr's four
    /// `Load_IPBin()` patches, and executes 0x8c00e000 (its second bootstrap)
    /// rather than the upload address. Without this the host only ever placed
    /// the single header sector and entered the binary directly, so the code a
    /// real disc runs between the two never ran at all -- and SA2 is the one
    /// title measured reading structures out of that region.
    ///
    /// Needs the loader out of the way: at the stock base dcload's own image
    /// covers 0x8c008000, so this is refused there rather than shooting the
    /// loader mid-upload.
    #[arg(long)]
    boot_ipbin: bool,

    #[command(subcommand)]
    command: Commands,
}

#[derive(clap::ValueEnum, Clone, Copy, Debug, Default, PartialEq, Eq)]
enum DescrambleArg {
    #[default]
    Auto,
    Always,
    Never,
}

impl From<DescrambleArg> for disc_formats::boot::Descramble {
    fn from(a: DescrambleArg) -> Self {
        match a {
            DescrambleArg::Auto => Self::Auto,
            DescrambleArg::Always => Self::Always,
            DescrambleArg::Never => Self::Never,
        }
    }
}

/// The bytes to upload, and what to call them in the log and on the bar.
///
/// POINT AT THE IMAGE, NOT AT A FILE YOU EXTRACTED FROM IT. A disc already says
/// which file it boots (IP.BIN names it) and where that file is, so extracting
/// `1ST_READ.BIN` by hand and then passing two paths that have to agree is work
/// nobody needs to do -- and one of the two being stale is a whole debugging
/// session.
/// `opened` is the image already open for the syscall loop, when the thing
/// being run IS that image -- which is the usual case, and re-opening it here
/// would re-read the zip directory and re-probe every track for nothing.
fn resolve_payload(
    args: &Args,
    file: &str,
    opened: Option<&dyn disc_formats::types::DiscFormat>,
) -> Result<(Vec<u8>, String), String> {
    let boot = match opened {
        Some(disc) => Some(
            disc_formats::boot::extract(disc, args.descramble.into())
                .map_err(|e| format!("{file}: {e}"))?,
        ),
        None if dispatch::is_disc_image(file) => {
            Some(dispatch::boot_binary(file, args.descramble.into())?)
        }
        None => None,
    };
    if let Some(boot) = boot {
        info!(
            "{file}: booting {} ({} bytes, LBA {})",
            boot.name,
            indicatif::HumanBytes(boot.bytes.len() as u64),
            boot.lba
        );
        return Ok((boot.bytes, boot.name));
    }
    dispatch::payload_from_file(std::path::Path::new(file)).map_err(|e| format!("{file}: {e}"))
}

/// Which image serves the title's disc reads.
///
/// When the thing being run IS a disc image, it is also the disc -- that is the
/// whole point of pointing at it. An explicit `-d` still wins, and `-m` (host
/// filesystem instead of a disc) turns it off.
fn effective_disc(file: &str, disc: &Option<String>, mount: &Option<String>) -> Option<String> {
    if disc.is_some() {
        return disc.clone();
    }
    if mount.is_some() {
        return None;
    }
    dispatch::is_disc_image(file).then(|| file.to_string())
}

/// `ADDR=N[:PEEK]` for `--probe`. N is 1..=127.
///
/// Without PEEK, N only names the probe and the reported buffer is the stub's
/// own literal pool -- "this address was executed" and nothing more.
///
/// With PEEK, the stub reports N bytes read FROM PEEK instead, so reaching the
/// site also exfiltrates memory: `--probe 0x8c0100f2=4:0x8c0000bc` says "when
/// the title gets here, show me the four bytes of the GD syscall vector". That
/// is the only way to look at the title's RAM at a chosen instant, because
/// dcload does not run again until a GD syscall and a probe stops the title
/// before one can happen.
fn parse_probe(s: &str) -> Result<(u32, u8, Option<u32>), String> {
    let (addr, rest) = s
        .split_once('=')
        .ok_or_else(|| format!("expected ADDR=N[:PEEK], got '{s}'"))?;
    let (n, peek) = match rest.split_once(':') {
        Some((n, p)) => (n, Some(p)),
        None => (rest, None),
    };
    let num = |t: &str| -> Result<u32, String> {
        let t = t.trim();
        let r = if let Some(h) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
            u32::from_str_radix(h, 16)
        } else {
            t.parse::<u32>()
        };
        r.map_err(|e| format!("'{t}': {e}"))
    };
    let addr = num(addr)?;
    let n = num(n)?;
    if n == 0 || n > 127 {
        return Err(format!("probe length/id must be 1..=127, got {n}"));
    }
    let peek = peek.map(num).transpose()?;
    Ok((addr, n as u8, peek))
}

/// `ADDR=VALUE`, both decimal or 0x-hex, for `--patch`.
fn parse_patch(s: &str) -> Result<(u32, u32), String> {
    let (addr, value) = s
        .split_once('=')
        .ok_or_else(|| format!("expected ADDR=VALUE, got `{s}`"))?;
    Ok((
        maybe_hex::<u32>(addr.trim())?,
        maybe_hex::<u32>(value.trim())?,
    ))
}

/// Work out which base the loader should be at for this disc, and say why.
///
/// Returns `None` when there is no reason to move: no disc, no database, no
/// match. The caller keeps the running loader in that case, which is the stock
/// 0x8c004000 and is what every title got before any of this existed.
/// Where to put the loader when the preset's own address is one the title
/// addresses. `None` means there is nowhere better.
///
/// One function, called by `uexec` and by `identify`, because the whole value
/// of the offline report is that it says what a run would actually do.
fn pick_clear_base(
    loaders: &loaders::LoaderSet,
    boot: &[u8],
    address: u32,
    wanted: u32,
    seen: Option<&memmap::MemoryMap>,
) -> Option<u32> {
    // WHAT THE TITLE HAS BEEN SEEN USING BEATS WHAT IT MENTIONS.
    //
    // The constant scan is a guess about an allocator and misses every failure
    // measured so far; `game-memory.tsv` is where reads actually landed, in
    // earlier sessions of this same game. Tried with a margin first, because
    // 0x8cfd0000 overlapped nothing and still froze 41 KB from the textures,
    // then without, then not at all -- a rich map must narrow the choice, never
    // empty it.
    for margin in [0x4_0000u32, 0] {
        let strict = |b: u32| base_is_clear(boot, address, b, seen, margin);
        if let Some(found) = choose(loaders, wanted, &strict) {
            if margin == 0 {
                warn!(
                    "0x{found:08x} is clear of where this title's reads have landed, but only \
                     just -- no base was clear of them with room to spare"
                );
            }
            return Some(found);
        }
    }
    if let Some(m) = seen.filter(|m| !m.is_empty()) {
        warn!(
            "every base this host can offer is inside RAM this title has been seen using \
             ({} of 256 blocks of 64 KB); falling back to constants alone, and the result \
             is a guess",
            m.blocks_marked()
        );
    }
    let is_clear = |b: u32| dispatch::literals_in_loader_footprint(boot, address, b).is_empty();
    choose(loaders, wanted, &is_clear)
}

/// The two tests that decide whether a base is safe for a title: what the title
/// NAMES (constants in its binary) and where its reads have LANDED (the learned
/// map). One definition, because it is asked in three places -- of the base a
/// preset wants, of each alternative, and of the base the loader is already at
/// -- and an answer that differed between them would be worse than no answer.
fn base_is_clear(
    boot: &[u8],
    address: u32,
    base: u32,
    seen: Option<&memmap::MemoryMap>,
    margin: u32,
) -> bool {
    dispatch::literals_in_loader_footprint(boot, address, base).is_empty()
        && !map_hits_loader(base, seen, margin)
}

/// Has this title been seen reading into RAM a loader at `base` would be using?
///
/// Over `exclusive_footprint`, the SAME ranges the constant scan reads. Asking
/// the map about `base..base+LOADER_SPAN` flat is right for a high loader and
/// wrong for a low one, whose span is the BIOS work area: every title uses low
/// RAM, so that test rejects the stock base for all of them. Sonic Adventure's
/// row marks 0x8c030000, and 0x8c004000 is the address 593 presets ask for and
/// the one that title is measured to run at.
fn map_hits_loader(base: u32, seen: Option<&memmap::MemoryMap>, margin: u32) -> bool {
    seen.is_some_and(|m| {
        loaders::exclusive_footprint(base)
            .into_iter()
            .any(|(lo, hi)| m.hits(lo, hi - lo, margin))
    })
}

/// Where to put the loader when the preset's address is one this host cannot
/// build at all -- 276 of the database's 1026 rows, every one of them below the
/// BIOS syscall area.
///
/// THE PRESET STILL ANSWERS, IN THE NEGATIVE. `ruled_out_by_low_preset` is that
/// reading: DreamShell reached for 0x8ce00000 and then 0x8cfe8000 before it gave
/// up and went low, so those two are the last places this title's loader should
/// go -- and "stay where you happen to be" lands on the first of them, because
/// it is also the address every chainload bounces through.
///
/// What is left is the map. The seed is the middle of the biggest run of RAM
/// this title has never been seen using; with no map at all that is the middle
/// of the relocatable window, which is a guess and is logged as one.
fn base_for_low_preset(
    loaders: &loaders::LoaderSet,
    boot: &[u8],
    address: u32,
    seen: Option<&memmap::MemoryMap>,
) -> Option<u32> {
    // FROM THE END OF THIS TITLE'S OWN IMAGE, not from the constant floor. For a
    // title whose preset cannot be honoured, that constant is exactly what has
    // to give: Jet Set Radio leaves one 64 KB block above 0x8ce00000, with its
    // own data hard against both sides of it, and 12.4 MB below.
    let image_end = ((address & 0x1fff_ffff) | 0x8c00_0000).saturating_add(boot.len() as u32);
    let (lo, hi) = loaders::window_above_image(image_end);
    let map = seen.copied().unwrap_or_default();
    let (run_lo, run_hi, seed) = map
        .free_runs(lo, hi)
        .into_iter()
        .find_map(|(a, b)| loaders::base_in_span(a, b).map(|s| (a, b, s)))?;
    info!(
        "this title's image ends at 0x{image_end:08x}, so a loader may go anywhere from \
         0x{lo:08x} up; the biggest stretch of that no disc read has ever landed in is \
         0x{run_lo:08x}..0x{run_hi:08x} ({} KB), and its middle is 0x{seed:08x}",
        (run_hi - run_lo) / 1024
    );
    for margin in [0x4_0000u32, 0] {
        let is_clear = |b: u32| {
            !loaders::ruled_out_by_low_preset(b) && base_is_clear(boot, address, b, seen, margin)
        };
        let clear: Vec<u32> = loaders
            .available()
            .into_iter()
            .filter(|&b| is_clear(b))
            .collect();
        // A base someone linked and ran outranks one this pass merely believes
        // in -- the same order `choose` uses, and for the same reason.
        if clear.contains(&seed) {
            return Some(seed);
        }
        if let Some(built) = loaders::nearest_clear_base(seed, &clear) {
            return Some(built);
        }
        if loaders.relocatable().is_some()
            && let Some(found) = loaders::search_free_base_above(lo, seed, is_clear)
        {
            return Some(found);
        }
    }
    None
}

/// The pre-built set first, then relocation -- for whatever "clear" means to
/// the caller.
fn choose(
    loaders: &loaders::LoaderSet,
    wanted: u32,
    is_clear: &dyn Fn(u32) -> bool,
) -> Option<u32> {

    // THE PRE-BUILT SET FIRST. Relocation answers what it cannot.
    //
    // Three measurements on Sonic Adventure 2, whose preset is 0x8cfe8000,
    // settle this — and the middle one is why "nearest to the preset" is NOT
    // the rule, though it was for an afternoon:
    //
    //   0x8cef8000  the game and its Kart mode both run
    //   0x8cfd0000  freezes loading COURSE.PVM, the Kart's track textures,
    //               which it decompresses into ~0x8cfc0000..0x8cfc6000 —
    //               41 KB under that base
    //   0x8ce00000  Kart is a black screen; it streams KART.ADX into
    //               0x8ce3a920, 182 KB above that base
    //
    // Being near the preset is worth nothing on its own: DreamShell picked
    // 0x8cfe8000 for isoldr, whose network build is 13 KB and fits the 32 KB
    // hole between the title's texture buffers and its Maple DMA list. Ours
    // needs 56 KB and does not fit that hole at all, so "just below the preset"
    // lands in the texture buffers and "well below" lands in the audio heap.
    // 0x8cef8000 works because it is in neither — and the only reason anyone
    // knows that is that someone ran it.
    //
    // So a base someone linked and ran outranks one this pass merely believes
    // in, and the constant scan's blind spot is exactly why: it sees addresses
    // a title NAMES, and every failure above was an allocator, which names
    // none. `receive_syscalls` reports how close reads actually come, which is
    // the evidence this choice cannot have in advance.
    let clear: Vec<u32> = loaders.available().into_iter().filter(|&b| is_clear(b)).collect();
    if let Some(built) = loaders::nearest_clear_base(wanted, &clear) {
        return Some(built);
    }
    // SAME FAMILY IN THE RELOCATION BRANCH TOO, not just in `nearest_clear_base`.
    // `search_free_base` walks a window that is entirely high, so without this a
    // low `wanted` is answered with a high base -- which is the collision a low
    // preset exists to avoid. Sonic Adventure is the case: preset 0x8c004000,
    // and a map marking 0x8ce00000..0x8cef0000. This used to be a consequence of
    // relocation being unable to produce a low image at all; it now stands on
    // its own, and is the only thing keeping the families apart here.
    if !loaders::is_high(wanted) {
        return None;
    }
    loaders
        .relocatable()
        .is_some()
        .then(|| loaders::search_free_base(wanted, is_clear))
        .flatten()
        .filter(|&b| b != wanted)
}

fn wanted_loader_base(
    args: &Args,
    running: Option<u32>,
    disc: Option<(&dyn disc_formats::types::DiscFormat, &str)>,
) -> Option<u32> {
    if args.no_relocate {
        return None;
    }
    if let Some(base) = args.loader_base {
        info!("loader base 0x{base:08x} (from --loader-base)");
        return Some(base);
    }
    let (disc, disc_path) = disc?;

    let identity = match dispatch::identify(disc, disc_path) {
        Ok(id) => id,
        Err(reason) => {
            // A warning, not a debug line, and it carries the reason. This is
            // the last point at which a bad `-d` path is cheap to notice: the
            // run continues, the title is uploaded, and every disc read it
            // makes afterwards fails.
            warn!("{reason}");
            warn!("cannot choose a loader base for this title; keeping the loader where it is");
            return None;
        }
    };
    info!(
        "disc: {} [{} {} {}] boot-sector md5 {}",
        identity.title, identity.product, identity.version, identity.region, identity.md5
    );

    let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
    let (db_path, db_searched) = game_db_path(args, &loaders);

    let db = match presets::PresetDb::load(&db_path) {
        Ok(db) => db,
        Err(e) => {
            warn!(
                "no game database at {} ({e}); every title will run at the loader's \
                 current address. Generate it with dcload-ip's scripts/make-preset-db.py \
                 and put game-presets.tsv in this project's root. Looked in: {}.",
                db_path.display(),
                db_searched
            );
            return None;
        }
    };
    debug!("game database: {} rows from {}", db.len(), db_path.display());

    // NOT AN EARLY RETURN ANY MORE. "Not in the database" used to mean "keep the
    // loader where it is", decided without ever looking at where that was -- and
    // where it is need not be the stock base: a chainload leaves the loader
    // wherever the last title needed it, and the next title inherits that. The
    // answer is worked out below with the boot binary and the map in hand, like
    // every other one.
    let found = db.lookup(&identity);
    if found.is_none() {
        info!(
            "'{}' is not in the game database ({} rows); nothing prescribes an address \
             for it",
            identity.title,
            db.len()
        );
    }
    if let Some((preset, kind)) = &found {
        // The whole row, once, for anyone reconstructing a session from the log.
        // `dma` and `fastboot` describe DreamShell's own storage device and menu
        // and mean nothing on a network transport; `async` is isoldr's sectors-per
        // -request, which dcload fixes at 8 (GD_EMU_ASYNC) at build time.
        debug!(
            "preset: memory={:08x} async={} dma={} irq={} cdda={:08x} heap={:08x} \
             low={} fastboot={} type={} mode={} altread={}",
            preset.memory, preset.emu_async, preset.dma, preset.irq, preset.cdda,
            preset.heap, preset.low, preset.fastboot, preset.bin_type,
            preset.boot_mode, preset.altread
        );

        match kind {
            presets::MatchKind::BootSectorMd5 => info!(
                "matched '{}' exactly (boot-sector md5): loader wants 0x{:08x}",
                preset.title, preset.memory
            ),
            presets::MatchKind::Title => {
                let ambiguity = db.title_ambiguity(&identity.title);
                if ambiguity > 1 {
                    warn!(
                        "matched '{}' BY TITLE ONLY, and presets under that title disagree \
                         about the address ({} different values); using 0x{:08x}. Pin it with \
                         --loader-base if this dump misbehaves.",
                        preset.title, ambiguity, preset.memory
                    );
                } else {
                    info!(
                        "matched '{}' by title (this exact dump is not in the database): \
                         loader wants 0x{:08x}",
                        preset.title, preset.memory
                    );
                }
            }
        }

        // Say what the preset asked for that this host does not do. When a title
        // misbehaves, "its preset wanted interrupt hooking and we dropped it" is
        // the first thing worth knowing, and it is invisible otherwise.
        for note in preset.unsupported() {
            warn!("'{}': not honoured -- {}", preset.title, note);
        }
    }

    // A PRESET CAN ASK FOR A BASE THE TITLE ITSELF WRITES TO.
    //
    // DreamShell's addresses are chosen for isoldr, whose network build is
    // 13 KB; ours reserves 0xe000 from the base for image, stack, packet
    // buffers and Maple buffer, so a base that leaves isoldr room can leave us
    // none. Sonic Adventure 2 is the measured case: preset 0x8cfe8000, and its
    // own Maple DMA list at 0x8cff0000, which is our stack. The console then
    // goes quiet with nothing logged at either end -- the DMA is written by the
    // hardware, so neither dcload nor this host is in the path (AGENTS.md 4.12
    // has the other cause with the same silence). 0x8cef8000 runs it perfectly.
    //
    // Checked here, from the disc's own boot binary, because this is the last
    // moment the base can still be changed: the relocation happens before the
    // title is uploaded. It re-reads the boot binary that `resolve_payload`
    // will read again -- a megabyte or two, against a session that would end in
    // a black screen with no way to tell why.
    let boot = match disc_formats::boot::extract(disc, args.descramble.into()) {
        Ok(b) => b.bytes,
        Err(e) => {
            // Not fatal, and not silent: the base stands, and if it does
            // collide this line is the only warning there will ever be. A
            // preset this host cannot build is no better than none here --
            // without the binary there is nothing to choose a substitute with.
            let unchecked = found
                .as_ref()
                .map(|(p, _)| p.memory)
                .filter(|&m| loaders::known_unsupported(m).is_none());
            match unchecked {
                Some(m) => warn!(
                    "could not read the boot binary to check it against the loader's \
                     address ({e}); using 0x{m:08x} unchecked"
                ),
                None => warn!(
                    "could not read the boot binary to check it against the loader's \
                     address ({e}); leaving the loader where it is, unchecked"
                ),
            }
            return unchecked;
        }
    };

    // WHICH ADDRESSES WERE ON THE TABLE, not just the one that won. Measured
    // 2026-08-27: a run picked 0x8ce00000 when the policy says 0x8cef8000,
    // because the loader set it was reading did not have the latter -- and the
    // log gave no way to tell. The set is deployed by hand (AGENTS.md 16), so
    // "which loaders were actually there" is a real question with a silent
    // wrong answer.
    info!(
        "loader candidates in {}: {}",
        loaders.dir().display(),
        if loaders.available().is_empty() {
            "none".to_string()
        } else {
            loaders
                .available()
                .iter()
                .map(|b| format!("0x{b:08x}"))
                .collect::<Vec<_>>()
                .join(", ")
        }
    );
    let memory_path = memory_db_path(args, &loaders);
    let seen_db = memmap::MemoryDb::load(&memory_path);
    let seen = seen_db.get(&identity.md5).map(|r| r.map);
    match seen.as_ref() {
        Some(m) => info!(
            "memory map: this title has been seen using {} of 256 blocks of RAM ({}, {} games)",
            m.blocks_marked(),
            memory_path.display(),
            seen_db.len()
        ),
        None => info!(
            "memory map: nothing recorded for this game yet ({}, {} games); \
             this session will start one",
            memory_path.display(),
            seen_db.len()
        ),
    }
    // NOTHING IN THE DATABASE PRESCRIBES AN ADDRESS, SO THE LOADER STAYS -- BUT
    // "STAYS" IS A DECISION, and this is the first point at which this host
    // checks it. It used to be taken before the boot binary or the map had been
    // read, on the assumption that where the loader is, is the stock base; a
    // chainload leaves it wherever the last title needed it, and 0x8ce00000 is
    // where every chainload passes through.
    let Some((preset, _)) = &found else {
        let running = running?;
        if base_is_clear(&boot, args.address, running, seen.as_ref(), 0x4_0000) {
            info!("keeping the loader where it is, at 0x{running:08x}");
            return None;
        }
        warn!(
            "'{}' is not in the database, and 0x{running:08x} -- where the loader \
             already is -- is RAM this title addresses or has been seen reading into. \
             Looking for somewhere else.",
            identity.title
        );
        return pick_clear_base(&loaders, &boot, args.address, running, seen.as_ref());
    };

    // A PRESET THIS HOST CANNOT BUILD IS THE STRONGEST STATEMENT IN THE
    // DATABASE, NOT A MISSING ONE.
    //
    // It used to end the decision: `ensure_loader_base` refused the address and
    // kept the loader where it was. That is the one answer the preset positively
    // excludes -- DreamShell went below the BIOS syscall area only after
    // 0x8ce00000 and 0x8cfe8000 had both failed for this title, and 0x8ce00000
    // is exactly where a loader that has been chainloaded is sitting.
    //
    // Measured 2026-08-28 on Jet Set Radio (preset 0x8c000100): the host stayed
    // at 0x8ce00000, the constant scan reported the title loading that very
    // address, the run was started anyway, and the 81st disc read of the boot
    // landed on the loader. Nothing had asked whether staying was safe.
    if let Some(reason) = loaders::known_unsupported(preset.memory) {
        warn!(
            "'{}': its preset asks for 0x{:08x}, which this host cannot build -- {reason}. \
             DreamShell puts isoldr below the BIOS syscall area only after its default \
             (0x{:08x}) and its high option (0x{:08x}) have both been rejected for a \
             title, so those two are ruled out here as well.",
            preset.title,
            preset.memory,
            loaders::ISOLDR_DEFAULT_ADDR,
            loaders::ISOLDR_HIGH_ADDR,
        );
        return match base_for_low_preset(&loaders, &boot, args.address, seen.as_ref()) {
            Some(alt) => {
                warn!(
                    "'{}': using 0x{alt:08x}, the address furthest from anything this \
                     title is known to touch; pin it with --loader-base to override.",
                    preset.title
                );
                Some(alt)
            }
            None => {
                error!(
                    "'{}': its preset cannot be built and nothing clear of this title \
                     could be produced either. The loader stays where it is: if the \
                     console goes silent with nothing logged, this is why.",
                    preset.title
                );
                None
            }
        };
    }
    let hits = dispatch::literals_in_loader_footprint(&boot, args.address, preset.memory);

    // THE PRESET IS THE ANSWER UNLESS SOMETHING SAYS OTHERWISE, and there are
    // exactly two things that can: what the title NAMES (constants in its
    // binary) and where its reads have LANDED (the learned map). DreamShell's
    // address is isoldr's own answer for this game and is right far more often
    // than any rule of ours -- it is only wrong when our 0xe000 does not fit
    // where isoldr's 13 KB did.
    //
    // The map is consulted for the preset itself, not just for the
    // alternatives. It used to be checked only after the constant scan had
    // already rejected the preset, which meant a game whose map said "the
    // preset is in the middle of my texture buffers" was sent there anyway --
    // the one case where the map has something to say and nothing to say it
    // about.
    // THE SAME TEST AS EVERYWHERE ELSE, which this line was not: it asked the map
    // about a flat span, and so ruled out the stock base for every title that
    // uses low RAM -- all of them.
    let seen_hits_preset = map_hits_loader(preset.memory, seen.as_ref(), 0x4_0000);
    if hits.is_empty() && !seen_hits_preset {
        return Some(preset.memory);
    }
    if hits.is_empty() {
        warn!(
            "'{}' has been seen using RAM within 256 KB of 0x{:08x}, the address its preset \
             asks for, though nothing in its binary names it. Looking for somewhere else.",
            preset.title, preset.memory
        );
    }
    match pick_clear_base(&loaders, &boot, args.address, preset.memory, seen.as_ref()) {
        Some(alt) => {
            if hits.is_empty() {
                warn!(
                    "'{}': using 0x{alt:08x} instead of the preset's 0x{:08x}, which this \
                     title's own memory map rules out; pin it with --loader-base to override.",
                    preset.title, preset.memory
                );
            } else {
                warn!(
                    "'{}' addresses RAM the loader would occupy at 0x{:08x}: {} constant(s) \
                     point inside it, the first at 0x{:08x} (loaded at 0x{:08x}). A write \
                     there -- and a Maple DMA list is filled by the hardware itself -- \
                     overwrites the loader with no syscall, no packet and no exception. \
                     Using 0x{alt:08x} instead; pin it with --loader-base to override.",
                    preset.title,
                    preset.memory,
                    hits.len(),
                    hits[0].0,
                    hits[0].1,
                );
            }
            Some(alt)
        }
        None => {
            error!(
                "'{}': 0x{:08x} is ruled out ({} constant(s) point into it{}), and nothing \
                 clear of it can be produced. Going ahead there anyway: if the console goes \
                 silent with nothing logged, this is why.",
                preset.title,
                preset.memory,
                hits.len(),
                if seen_hits_preset {
                    ", and its reads have landed nearby"
                } else {
                    ""
                },
            );
            Some(preset.memory)
        }
    }
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Upload a binary and execute it immediately
    UExec {
        /// What to run: a binary (1ST_READ.BIN, an ELF), or a DISC IMAGE.
        ///
        /// Given an image (.gdi / .cdi / .iso, or a .zip holding one), the boot
        /// binary is read out of it and the same image serves the title's disc
        /// reads -- no extracting anything, and no second path to keep in step.
        #[arg(value_hint = clap::ValueHint::FilePath)]
        file: String,

        /// Path to file to redirect the reads to
        #[arg(short, long, value_hint = clap::ValueHint::FilePath, conflicts_with = "mount")]
        disc: Option<String>,

        #[arg(short, long, value_hint = clap::ValueHint::DirPath)]
        mount: Option<String>,

        /// Enable console redirection
        #[arg(short, long)]
        console: bool,
    },
    /// Upload a binary
    Upload {
        /// Path to file to upload. A disc image works here too: its boot binary
        /// is what gets uploaded.
        #[arg(value_hint = clap::ValueHint::FilePath)]
        file: String,
    },
    /// Write a disc image's boot binary out to a file.
    ///
    /// Touches no network. Mostly a way to check what `uexec <image>` is going
    /// to send before sending it -- and the only offline test there is that a
    /// zipped image reads back byte for byte like the loose one.
    Extract {
        /// Disc image (.gdi / .cdi / .iso / .zip)
        #[arg(value_hint = clap::ValueHint::FilePath)]
        disc: String,

        /// Where to write it. Default: the name the disc gives it, in the
        /// current directory.
        #[arg(short, long, value_hint = clap::ValueHint::FilePath)]
        output: Option<String>,
    },
    /// Reboot the console (only works when dcload is in control)
    Reboot {},
    /// Write known patterns to free RAM and read them straight back, across
    /// several sizes and misalignments. Uploads no title and starts nothing --
    /// it only answers "can a read-back off this console be believed at all".
    SelftestReadback {},
    /// Read a disc image and print what it is and which loader base it wants.
    ///
    /// Touches no network and needs no Dreamcast, which is the point: when a
    /// title misbehaves, this separates "the image is not what you think" from
    /// "the console did something odd" in one command.
    Identify {
        /// Disc image (.gdi / .cdi / .iso, or a .zip holding one -- add
        /// `#member` to pick one out of an archive with several)
        #[arg(value_hint = clap::ValueHint::FilePath)]
        disc: String,
    },
    /// Move a relocatable loader ELF to another base and write it out.
    ///
    /// The same relocation `uexec` performs in memory, exposed so it can be
    /// inspected, diffed against a native build, or kept. Needs no Dreamcast
    /// and no SH toolchain.
    Relocate {
        /// The loader to move (loaders/dcload-relocatable.elf)
        #[arg(value_hint = clap::ValueHint::FilePath)]
        elf: String,
        /// Base to move it to, e.g. 0x8cef8000
        #[arg(value_parser = maybe_hex::<u32>)]
        to: u32,
        /// Where to write the result
        #[arg(short, long, value_hint = clap::ValueHint::FilePath)]
        output: String,
    },
}

/// `identify`: everything the loader-placement pass would work out, printed.
fn identify_only(args: &Args, disc: &str) -> ExitCode {
    let reader = match dispatch::open_disc(disc) {
        Ok(d) => d,
        Err(reason) => {
            error!("{reason}");
            return ExitCode::FAILURE;
        }
    };
    let identity = match dispatch::identify(reader.as_ref(), disc) {
        Ok(id) => id,
        Err(reason) => {
            error!("{reason}");
            return ExitCode::FAILURE;
        }
    };
    println!("title    : {}", identity.title);
    println!("product  : {} {}", identity.product, identity.version);
    println!("region   : {}", identity.region);
    println!("boot md5 : {}", identity.md5);
    let boot_bytes = match disc_formats::boot::extract(reader.as_ref(), args.descramble.into()) {
        Ok(b) => {
            println!(
                "boot bin : {} ({} bytes at LBA {}){}",
                b.name,
                b.bytes.len(),
                b.lba,
                match (b.scrambling, b.descrambled) {
                    (_, true) => " -- unscrambled",
                    (disc_formats::scramble::Scrambling::Plain, _) => " -- plain",
                    _ => "",
                }
            );
            println!("bin md5  : {:x}", md5::compute(&b.bytes));
            Some(b.bytes)
        }
        Err(e) => {
            println!("boot bin : NOT FOUND -- {e}");
            None
        }
    };

    let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());

    // Does the title address the RAM the loader would be sitting in? Answered
    // HERE because it needs no console: a collision found offline costs one
    // command, and the same collision found on hardware costs a session that
    // ends with a black screen and nothing logged (see
    // `literals_in_loader_footprint`).
    // The same memory `uexec` would consult, so the offline report answers with
    // what a run would actually pick.
    let seen_db = memmap::MemoryDb::load(&memory_db_path(args, &loaders));
    let seen = seen_db.get(&identity.md5).map(|r| r.map);
    match seen.as_ref() {
        Some(m) => println!(
            "seen     : {} of 256 blocks of 64 KB used in earlier sessions \
             (of {} games recorded)",
            m.blocks_marked(),
            seen_db.len()
        ),
        None => println!(
            "seen     : nothing recorded for this game yet (of {} games recorded)",
            seen_db.len()
        ),
    }
    let report_collisions = |base: u32| {
        let Some(bytes) = boot_bytes.as_deref() else {
            return;
        };
        let hits = dispatch::literals_in_loader_footprint(bytes, args.address, base);
        let where_ = loaders::live_footprint(base)
            .iter()
            .map(|(lo, hi)| format!("0x{lo:08x}..0x{hi:08x}"))
            .collect::<Vec<_>>()
            .join(" and ");
        if hits.is_empty() {
            println!("overlap  : none -- nothing the title loads points into {where_}");
            return;
        }
        println!(
            "overlap  : {} CONSTANT(S) POINT INTO THE LOADER at {where_}",
            hits.len()
        );
        for (at, site) in hits.iter().take(8) {
            println!("           0x{at:08x} loaded at 0x{site:08x}");
        }
        println!(
            "           If the title writes there the loader is overwritten -- and a \
             Maple DMA does it with no syscall, no packet and no exception."
        );
        // The same policy `uexec` applies, out of the same function, so this
        // cannot drift from what a run would actually do. The answer is what
        // the reader actually needs; without it "pick another base" is an
        // invitation to guess, and a guess costs a session per attempt.
        match pick_clear_base(&loaders, bytes, args.address, base, seen.as_ref()) {
            Some(alt) => println!(
                "           uexec would use 0x{alt:08x} instead ({}).",
                if loaders.has(alt) {
                    "a loader built for that address".to_string()
                } else {
                    format!("relocating {} there -- no rebuild", loaders::RELOCATABLE_NAME)
                }
            ),
            None => println!(
                "           Nowhere clear of it, so uexec would go ahead here. Note this \
                 only sees constants: a heap that grows into the loader has none."
            ),
        }
    };
    let (db_path, db_searched) = game_db_path(args, &loaders);
    match presets::PresetDb::load(&db_path) {
        Err(e) => println!(
            "preset   : no database at {} ({e})\n           looked in: {}",
            db_path.display(),
            db_searched
        ),
        Ok(db) => match db.lookup(&identity) {
            None => {
                println!(
                    "preset   : not in the database ({} rows); would stay at 0x{:08x}",
                    db.len(),
                    loaders::DEFAULT_BASE
                );
                report_collisions(loaders::DEFAULT_BASE);
            }
            Some((p, kind)) => {
                let how = match kind {
                    presets::MatchKind::BootSectorMd5 => "exact (boot-sector md5)".to_string(),
                    presets::MatchKind::Title => {
                        let n = db.title_ambiguity(&identity.title);
                        if n > 1 {
                            format!("BY TITLE, ambiguous ({n} different addresses)")
                        } else {
                            "by title".to_string()
                        }
                    }
                };
                println!("preset   : '{}' -- {}", p.title, how);
                println!("memory   : 0x{:08x}", p.memory);
                println!(
                    "loader   : {}",
                    if let Some(reason) = loaders::known_unsupported(p.memory) {
                        format!("UNSUPPORTED base -- {reason}")
                    } else if loaders.has(p.memory) {
                        format!("{} present", loaders.path_for(p.memory).display())
                    } else if loaders.can_provide(p.memory) {
                        format!(
                            "no dcload-0x{:08x}.elf, {} relocated to it",
                            p.memory,
                            loaders::RELOCATABLE_NAME
                        )
                    } else {
                        format!(
                            "MISSING dcload-0x{:08x}.elf in {} (looked in: {})",
                            p.memory,
                            loaders.dir().display(),
                            loaders.searched()
                        )
                    }
                );
                for note in p.unsupported() {
                    println!("not done : {note}");
                }
                // The same two functions `uexec` calls, so this report cannot
                // drift from what a run would do -- including for a preset this
                // host cannot build, where "would stay put" was the old answer
                // and is the one the preset rules out.
                if loaders::known_unsupported(p.memory).is_some() {
                    match boot_bytes
                        .as_deref()
                        .and_then(|b| base_for_low_preset(&loaders, b, args.address, seen.as_ref()))
                    {
                        Some(alt) => {
                            println!(
                                "would use: 0x{alt:08x} -- 0x{:08x} and 0x{:08x} are ruled out \
                                 by a preset this low",
                                loaders::ISOLDR_DEFAULT_ADDR,
                                loaders::ISOLDR_HIGH_ADDR
                            );
                            report_collisions(alt);
                        }
                        None => println!(
                            "would use: nothing clear of this title could be produced; the \
                             loader would stay where it is"
                        ),
                    }
                } else {
                    report_collisions(p.memory);
                }
            }
        },
    }
    ExitCode::SUCCESS
}

/// A filename taken out of a disc image, made safe to use as a host path.
///
/// The bytes at IP.BIN +0x60 are whatever was mastered there: `iso9660::
/// boot_file_name` stops at a NUL or a space and passes everything else
/// through, separators and `..` included. Only the last component survives
/// here, and only its plain-filename characters; anything else becomes `_`,
/// and a name that is left empty or is `.`/`..` falls back to the usual one.
fn safe_output_name(name: &str) -> String {
    let base = name.rsplit(['/', '\\', ':']).next().unwrap_or(name);
    let cleaned: String = base
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-') {
                c
            } else {
                '_'
            }
        })
        .collect();
    // A leading dot is the last thing left that the image gets to decide and
    // the user does not see: `.bashrc` lands in the working directory and does
    // not show up in an `ls`. No boot binary is named that way.
    let cleaned = cleaned.trim_start_matches('.');
    if cleaned.trim_matches('.').is_empty() {
        return "1ST_READ.BIN".to_string();
    }
    cleaned.to_string()
}

/// `extract`: the boot binary out of an image and onto disk.
fn extract_only(args: &Args, disc: &str, output: Option<&str>) -> ExitCode {
    let boot = match dispatch::boot_binary(disc, args.descramble.into()) {
        Ok(b) => b,
        Err(e) => {
            error!("{e}");
            return ExitCode::FAILURE;
        }
    };
    // `-o` is a path the USER typed and is taken as it lies. The default is
    // not: it comes out of IP.BIN's sixteen-byte filename field, byte for
    // byte, and nothing in the image stops that field reading `../../.bashrc`.
    // Writing it verbatim would let the image choose where the host writes.
    let default = safe_output_name(&boot.name);
    let out = output.unwrap_or(&default);
    if let Err(e) = std::fs::write(out, &boot.bytes) {
        error!("cannot write {out}: {e}");
        return ExitCode::FAILURE;
    }
    info!(
        "{} -> {out} ({} bytes, md5 {:x}){}",
        boot.name,
        boot.bytes.len(),
        md5::compute(&boot.bytes),
        if boot.descrambled { ", unscrambled" } else { "" }
    );
    ExitCode::SUCCESS
}

/// (the table to read, every path considered).
///
/// Resolved exactly like the loader set: beside the loaders, then in the
/// project root, and only then next to the executable -- so `cargo clean`
/// cannot take it and debug and release read the same file. The second half of
/// the pair exists because "no game database at X" names one path and leaves
/// the user guessing about the others.
fn game_db_path(args: &Args, loaders: &loaders::LoaderSet) -> (std::path::PathBuf, String) {
    let exe = std::env::current_exe().ok();
    let cwd = std::env::current_dir().ok();
    let candidates = loaders::game_db_candidates(
        args.game_db.clone(),
        std::env::var("DCLOAD_GAME_DB").ok(),
        loaders.dir(),
        exe.as_deref(),
        cwd.as_deref(),
        env!("CARGO_MANIFEST_DIR"),
    );
    let chosen = candidates
        .iter()
        .find(|p| p.is_file())
        .unwrap_or(&candidates[0])
        .clone();
    let searched = candidates
        .iter()
        .map(|p| p.display().to_string())
        .collect::<Vec<_>>()
        .join(", ");
    (chosen, searched)
}

/// Where the learned memory map is read from and written back to.
fn memory_db_path(args: &Args, loaders: &loaders::LoaderSet) -> std::path::PathBuf {
    let exe = std::env::current_exe().ok();
    let cwd = std::env::current_dir().ok();
    let candidates = loaders::memory_db_candidates(
        args.memory_db.clone(),
        std::env::var("DCLOAD_MEMORY_DB").ok(),
        loaders.dir(),
        exe.as_deref(),
        cwd.as_deref(),
        env!("CARGO_MANIFEST_DIR"),
    );
    if let Some(found) = candidates.iter().find(|p| p.is_file()) {
        return found.clone();
    }
    // Nothing yet, so this run creates it -- BESIDE THE PRESET DATABASE, not in
    // whichever directory happened to be searched first. The two are read
    // together, shipped together and committed together; a memory map that
    // lands somewhere else is one the next deployment does not carry.
    let (presets, _) = game_db_path(args, loaders);
    if let Some(dir) = presets.parent().filter(|d| d.is_dir()) {
        return dir.join("game-memory.tsv");
    }
    candidates[0].clone()
}

fn main() -> Result<ExitCode, Box<dyn std::error::Error>> {
    let args = Args::parse();
    // Logging goes through the progress display (see `ui`), so that a log
    // record never lands on top of a bar that is being drawn.
    ui::init_logging(args.verbose);
    // BEFORE anything can take time. A run spends its first seconds
    // chainloading a loader and pushing megabytes at the console, and a Ctrl-C
    // in that window used to be an outright kill because the handler was not
    // installed until the title was already running. This also starts the
    // ticker that keeps the learned memory map on disk -- read
    // `memmap::install_signal_handler` for why that ticker, and not the
    // handler, is what actually saves the file.
    memmap::install_signal_handler();
    // Before the socket: these never talk to a Dreamcast.
    if let Commands::Identify { ref disc } = args.command {
        return Ok(identify_only(&args, disc));
    }
    if let Commands::Relocate {
        ref elf,
        to,
        ref output,
    } = args.command
    {
        let bytes = match std::fs::read(elf) {
            Ok(b) => b,
            Err(e) => {
                error!("cannot read {elf}: {e}");
                return Ok(ExitCode::FAILURE);
            }
        };
        return Ok(match loaders::relocate(&bytes, to) {
            Ok(moved) => match std::fs::write(output, &moved) {
                Ok(()) => {
                    println!("{elf} -> {output}, based at 0x{to:08x} ({} bytes)", moved.len());
                    ExitCode::SUCCESS
                }
                Err(e) => {
                    error!("cannot write {output}: {e}");
                    ExitCode::FAILURE
                }
            },
            Err(e) => {
                error!("cannot relocate {elf}: {e}");
                ExitCode::FAILURE
            }
        });
    }
    if let Commands::Extract {
        ref disc,
        ref output,
    } = args.command
    {
        return Ok(extract_only(&args, disc, output.as_deref()));
    }

    let legacy_mode = protocol_version()[0] < 2;
    let remote_port = if legacy_mode { 31313 } else { args.port };
    let local_port = if legacy_mode { Some(31313) } else { None };
    let mut udpsender = DcIoUDP::new(args.host.clone(), remote_port, local_port)?;
    let (version_text, mut running_base) = match dispatch::query_loader(&mut udpsender) {
        Err(err) => {
            error!("Failed to contact the client: {}", err);
            return Ok(ExitCode::FAILURE);
        }
        Ok(v) => v,
    };
    info!(
        "Successfully connected to dcload-ip on host {} using port {}",
        args.host, args.port
    );
    match running_base {
        Some(base) => info!("dcload-ip version: {} (loaded at 0x{:08x})", version_text, base),
        None => info!(
            "dcload-ip version: {} (does not report its load address; \
             this build cannot be relocated per game)",
            version_text
        ),
    }

    // Which image answers the title's disc reads. Worked out once, here,
    // because it decides both where the loader goes and what the syscall loop
    // is handed -- and those two disagreeing is a session with the right game
    // running at the wrong address.
    let redirect_disc: Option<String> = match &args.command {
        Commands::UExec {
            file, disc, mount, ..
        } => effective_disc(file, disc, mount),
        _ => None,
    };

    // Opened ONCE, here, and handed to everything that needs it: the identity
    // pass, the boot binary, IP.BIN and the syscall loop. Each `open_disc`
    // re-reads a zip's central directory, re-probes every CDI track for a PVD
    // and re-opens every GDI track file -- only the deflate index survives
    // between opens -- so a run that opened per use paid for all of that four
    // times before the title started.
    //
    // A failure here is reported and is not fatal: the title is still uploaded
    // and started, exactly as before, and every disc read it makes then fails.
    let mut disc_reader: Option<Box<dyn disc_formats::types::DiscFormat>> = None;
    if let Some(path) = redirect_disc.as_deref() {
        match dispatch::open_disc(path) {
            Ok(disc) => disc_reader = Some(disc),
            Err(e) => {
                error!("CDFS redirection DISABLED: {e}");
                error!("the title will be started anyway, and every disc read it makes will fail");
            }
        }
    }

    // Relocate BEFORE uploading the title. Any chainload replaces the whole
    // loader, so a title uploaded first would be uploaded into an image that is
    // about to be overwritten -- and the game's own RAM is zero-filled by the
    // loader that comes up.
    if matches!(args.command, Commands::UExec { .. })
        && let Some(want) = wanted_loader_base(
            &args,
            running_base,
            disc_reader.as_deref().zip(redirect_disc.as_deref()),
        )
    {
        match running_base {
            Some(base) => {
                let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
                running_base = Some(dispatch::ensure_loader_base(
                    &mut udpsender,
                    &loaders,
                    base,
                    want,
                ));
            }
            None => warn!(
                "this title wants the loader at 0x{want:08x}, but the loader on the \
                 console does not report where it is, so it cannot be moved safely. \
                 Rebuild dcload-ip and re-burn its boot image (or re-run the CD/CDI) \
                 to get a loader that does."
            ),
        }
    }

    let result: Result<ExitCode, Box<dyn std::error::Error>> = match args.command {
        Commands::UExec {
            ref file,
            ref mount,
            console,
            ..
        } => {
            // A disc image resolves to the boot binary it names; anything else
            // is uploaded as it lies.
            // The same image, when `uexec <image>` was given without `-d`.
            let payload_disc = disc_reader
                .as_deref()
                .filter(|_| redirect_disc.as_deref() == Some(file.as_str()));
            let (payload, label) = match resolve_payload(&args, file, payload_disc) {
                Ok(p) => p,
                Err(e) => {
                    error!("{e}");
                    return Ok(ExitCode::FAILURE);
                }
            };
            let has_disc = redirect_disc.is_some();
            match dispatch::upload_bytes(
                &mut udpsender,
                &payload,
                &label,
                args.address,
                running_base,
            ) {
            Err(e) => Err(e),
            Ok((addr, _size)) => {
                // After the title, before EXEC: the region is clear of both.
                // `boot_ipbin` decides both how much of IP.BIN goes over and
                // where execution starts; if the load fails there is no
                // bootstrap in RAM, so fall back to entering the binary rather
                // than jumping into whatever was there before.
                let mut entry = addr;
                if let (Some(reader), Some(d)) = (disc_reader.as_deref(), redirect_disc.as_ref()) {
                    match dispatch::load_ip_bin(
                        &mut udpsender,
                        reader,
                        d,
                        running_base,
                        args.boot_ipbin,
                    ) {
                        Ok(true) if args.boot_ipbin => {
                            entry = dispatch::IP_BIN_BOOTSTRAP_2_EXEC;
                        }
                        Ok(false) if args.boot_ipbin => {
                            // Declined, not failed -- the loader is sitting on
                            // the region. Entering 0x8c00e000 now would jump
                            // into the loader's own image.
                            warn!(
                                "--boot-ipbin declined (see above); entering \
                                 0x{addr:08x} directly"
                            );
                        }
                        Ok(_) => {}
                        Err(e) => {
                            warn!("could not load IP.BIN: {e}");
                            if args.boot_ipbin {
                                warn!(
                                    "--boot-ipbin asked for, but IP.BIN is not in RAM; \
                                     entering 0x{addr:08x} directly instead"
                                );
                            }
                        }
                    }
                } else if args.boot_ipbin {
                    if has_disc {
                        warn!(
                            "--boot-ipbin asked for, but the disc image could not be \
                             opened (see above); entering 0x{addr:08x} directly"
                        );
                    } else {
                        warn!("--boot-ipbin needs a disc image; entering 0x{addr:08x} directly");
                    }
                }
                // SAID BEFORE THE TITLE STARTS, WHILE THE BASE CAN STILL
                // BE CHANGED -- because once it is running, nothing can say it.
                // A title that writes over the loader ends the session in
                // silence, and when it does it by DMA (Maple above all) not one
                // byte passes through dcload or through this host. The check is
                // one pass over the image for constants naming RAM the loader
                // occupies, kept honest by requiring an instruction to actually
                // load them.
                if let Some(base) = running_base {
                    let hits =
                        dispatch::literals_in_loader_footprint(&payload, args.address, base);
                    if !hits.is_empty() {
                        error!(
                            "THIS TITLE ADDRESSES RAM THE LOADER IS SITTING IN. The loader at \
                             0x{base:08x} occupies {}, and the title loads {} constant(s) \
                             pointing inside it. If it writes there -- and a Maple DMA list is \
                             filled by the hardware itself -- the loader is overwritten with no \
                             syscall, no packet and no exception: black screen, no further disc \
                             reads, nothing logged at either end. Try another base with \
                             --loader-base.",
                            crate::loaders::live_footprint(base)
                                .iter()
                                .map(|(lo, hi)| format!("0x{lo:08x}..0x{hi:08x}"))
                                .collect::<Vec<_>>()
                                .join(" and "),
                            hits.len(),
                        );
                        for (at, site) in hits.iter().take(8) {
                            error!("    0x{at:08x} loaded at 0x{site:08x}");
                        }
                    }
                }
                // Before --patch, so an explicit patch still wins over it.
                //
                // Kept, not dropped: the words this neutralises live in the
                // title's own image, which a title is free to reload from its
                // disc. `receive_syscalls` watches every read for one landing
                // on them and puts them back, so the guard survives a reload
                // instead of being undone by one.
                let mut gaps_guard: Vec<(u32, u32)> = vec![];
                if !args.no_gaps_guard {
                    gaps_guard = dispatch::gaps_probe_patches(&payload, args.address);
                    if !gaps_guard.is_empty()
                        && let Err(e) = dispatch::apply_patches(&mut udpsender, &gaps_guard)
                    {
                        warn!("could not neutralise the GAPS probe: {e}");
                    }
                }
                // Last, so a patch always wins over the bytes it replaces --
                // whether they came from the title, from IP.BIN, or from both.
                if !args.patch.is_empty()
                    && let Err(e) = dispatch::apply_patches(&mut udpsender, &args.patch)
                {
                    warn!("could not apply patches: {e}");
                }
                if !args.probe.is_empty()
                    && let Err(e) =
                        dispatch::apply_probes(&mut udpsender, &args.probe, running_base)
                {
                    warn!("could not place probes: {e}");
                }
                // Set up BEFORE the title starts, while the disc is still in
                // hand: from here on the reader belongs to the syscall loop.
                // A title with no identity records nothing rather than filing
                // its map under a name that could be any dump.
                let memory_recorder = disc_reader
                    .as_deref()
                    .zip(redirect_disc.as_deref())
                    .and_then(|(d, p)| dispatch::identify(d, p).ok())
                    .map(|id| {
                        let path = memory_db_path(&args, &loaders::LoaderSet::discover(
                            args.loader_dir.clone(),
                        ));
                        // What is already known, so the end-of-session report
                        // can say what THIS session added rather than how much
                        // there is in total.
                        let baseline = memmap::MemoryDb::load(&path)
                            .get(&id.md5)
                            .map(|r| r.map)
                            .unwrap_or_default();
                        info!("learning this title's memory map into {}", path.display());
                        std::sync::Arc::new(std::sync::Mutex::new(memmap::MemoryRecorder::new(
                            path, &id.md5, &id.title, baseline,
                        )))
                    });
                // From here the ticker installed at the top of main has
                // something to write, and a Ctrl-C has something to report.
                memmap::set_active(memory_recorder.clone());
                info!("Upload complete, executing at 0x{:08x}", entry);
                // The title is on the console now; the host's copy is only
                // holding up to 16 MiB for the length of the session.
                drop(payload);
                match dispatch::execute(&mut udpsender, entry, console || has_disc || mount.is_some(), has_disc) {
                    Err(e) => Err(e),
                    Ok(_) => {
                        if has_disc || mount.is_some() || console {
                            dispatch::receive_syscalls(
                                &mut udpsender,
                                disc_reader,
                                mount.clone(),
                                running_base,
                                &gaps_guard,
                                memory_recorder,
                            )?;
                            return Ok(ExitCode::SUCCESS);
                        }
                        Ok(ExitCode::SUCCESS)
                    }
                }
            }
        }},
        Commands::Upload { ref file } => {
            let (payload, label) = match resolve_payload(&args, file, None) {
                Ok(p) => p,
                Err(e) => {
                    error!("{e}");
                    return Ok(ExitCode::FAILURE);
                }
            };
            return match dispatch::upload_bytes(
                &mut udpsender,
                &payload,
                &label,
                args.address,
                running_base,
            )
            .map(|_s| ExitCode::SUCCESS)
            {
                Err(e) => Err(e),
                Ok(code) => {
                    info!("Upload complete");
                    Ok(code)
                }
            };
        }
        // Handled before the socket is opened; unreachable here, but spelled
        // out rather than caught by a wildcard so adding a subcommand keeps
        // failing to compile until it is wired up.
        Commands::Identify { .. } | Commands::Extract { .. } | Commands::Relocate { .. } => {
            unreachable!("handled before connecting")
        }
        Commands::SelftestReadback {} => {
            return match dispatch::selftest_readback(&mut udpsender)? {
                true => Ok(ExitCode::SUCCESS),
                false => Ok(ExitCode::FAILURE),
            };
        }
        Commands::Reboot {} => {
            info!("Sending reboot command");
            dispatch::reboot(&mut udpsender)?;
            info!("Reboot command sent");
            return Ok(ExitCode::SUCCESS);
        } // _ => Err(Box::new(NotImplemented {
          //     feature: "Unknown command".to_string(),
          // })),
    };
    if let Err(returned_error) = result {
        error!("{}", returned_error);
        Ok(ExitCode::FAILURE)
    } else {
        Ok(ExitCode::SUCCESS)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The default output name comes out of the IMAGE, and nothing in an image
    /// stops those sixteen bytes reading `../../.bashrc`. `extract` would then
    /// write there, with no confirmation and no overwrite check.
    #[test]
    fn an_image_cannot_choose_where_extract_writes() {
        assert_eq!(safe_output_name("1ST_READ.BIN"), "1ST_READ.BIN");
        assert_eq!(safe_output_name("0WINCEOS.BIN"), "0WINCEOS.BIN");
        for hostile in ["../../.bashrc", "/etc/cron.d/x", r"..\..\.bashrc"] {
            let out = safe_output_name(hostile);
            assert!(!out.contains('/') && !out.contains('\\'), "{hostile} -> {out}");
            assert!(!out.starts_with('.'), "{hostile} -> {out}");
        }
        assert_eq!(safe_output_name(".."), "1ST_READ.BIN");
        assert_eq!(safe_output_name(""), "1ST_READ.BIN");
    }

    /// Jet Set Radio's row after the session of 2026-08-28: the low buffer, the
    /// boot's ascending load truncated exactly where it overwrote the loader at
    /// 0x8ce00000, and the sector buffer the title keeps at the top of RAM.
    const JSR_BLOCKS: &str =
        "40000000000000000000000000000000000000000000000000e0ffff01000080";

    /// A raw boot binary whose only content is a `mov.l @(disp,PC),R1` loading
    /// `constant` -- the shape `literals_in_loader_footprint` reports, and the
    /// shape Jet Set Radio has at 0x8c013bde.
    fn boot_loading(constant: u32) -> Vec<u8> {
        let mut b = vec![0u8; 0x1000];
        b[0x200..0x204].copy_from_slice(&constant.to_le_bytes());
        let disp = (0x200 - ((0x100 + 4) & !3)) / 4;
        b[0x100..0x102].copy_from_slice(&(0xd100u16 | disp as u16).to_le_bytes());
        b
    }

    /// A `loaders/` directory holding names only: nothing on this path opens an
    /// ELF, it asks which bases exist and whether the relocatable image is there.
    fn fake_loader_dir(name: &str, bases: &[u32]) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(name);
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        for b in bases {
            std::fs::write(dir.join(format!("dcload-0x{b:08x}.elf")), []).unwrap();
        }
        std::fs::write(dir.join(loaders::RELOCATABLE_NAME), []).unwrap();
        dir
    }

    /// Sonic Adventure's row: it marks 0x8c030000, in the BIOS work area a low
    /// loader shares with the title by construction, and it marks
    /// 0x8ce00000..0x8cef0000, which is most of where a relocation could go.
    const SA_BLOCKS: &str =
        "0800000000000000000000000006007c024000ff0000f0000078ffffffff0000";

    #[test]
    fn the_stock_base_is_not_condemned_by_a_title_using_low_ram() {
        // The guard that fires on the one title known to work guards nothing
        // (AGENTS.md 14.9). Sonic Adventure's preset IS the stock base and it
        // is measured running there; judging that base on its flat span made
        // the map say otherwise.
        let map = memmap::MemoryMap::from_hex(SA_BLOCKS).unwrap();
        assert!(map.is_marked(3), "the fixture must reproduce 0x8c030000");
        assert!(!map_hits_loader(loaders::DEFAULT_BASE, Some(&map), 0x4_0000));

        // What a low loader DOES keep in high RAM is still judged: its packet
        // and Maple buffers at 0x8cfe8000 are in RAM a title owns outright.
        let mut buffers = memmap::MemoryMap::new();
        buffers.mark(0x8cfe_8000, 0x1000);
        assert!(map_hits_loader(loaders::DEFAULT_BASE, Some(&buffers), 0));
    }

    #[test]
    fn a_low_request_is_never_answered_with_a_high_base() {
        // Relocation moves a HIGH image and its window is entirely high, so
        // once the scan was clamped to that window a low `wanted` would have
        // been answered with a base in the RAM the preset exists to leave to
        // the title. The answer is no answer.
        let dir = fake_loader_dir("dcload-family", &[loaders::ISOLDR_DEFAULT_ADDR]);
        let set = loaders::LoaderSet::discover(Some(dir.to_string_lossy().into_owned()));
        let map = memmap::MemoryMap::from_hex(SA_BLOCKS).unwrap();
        // A title naming a low loader's packet buffers: the stock base really
        // is ruled out here, so this is not None for want of a reason.
        let boot = boot_loading(0x8cfe_8000);
        assert!(
            !dispatch::literals_in_loader_footprint(&boot, 0x0c01_0000, loaders::DEFAULT_BASE)
                .is_empty(),
            "the fixture does not rule out the base it is about"
        );
        assert_eq!(
            pick_clear_base(&set, &boot, 0x0c01_0000, loaders::DEFAULT_BASE, Some(&map)),
            None
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_preset_this_host_cannot_build_moves_the_loader_off_isoldrs_addresses() {
        let dir = fake_loader_dir("dcload-lowpreset", &[loaders::ISOLDR_DEFAULT_ADDR]);
        let set = loaders::LoaderSet::discover(Some(dir.to_string_lossy().into_owned()));
        let map = memmap::MemoryMap::from_hex(JSR_BLOCKS).unwrap();
        let boot = boot_loading(loaders::ISOLDR_DEFAULT_ADDR);

        // THE FIXTURE HAS TO REPRODUCE THE FAILURE BEFORE ITS ABSENCE MEANS
        // ANYTHING (AGENTS.md 14.9): 0x8ce00000 is where the loader was left,
        // and it is both a constant this title loads and a block it read into.
        assert!(
            !dispatch::literals_in_loader_footprint(
                &boot,
                0x0c01_0000,
                loaders::ISOLDR_DEFAULT_ADDR
            )
            .is_empty(),
            "the fixture does not reproduce the collision it is about"
        );
        assert!(map.hits(loaders::ISOLDR_DEFAULT_ADDR, loaders::LOADER_SPAN, 0));

        // The middle of the biggest stretch no disc read has ever landed in.
        // NOT 0x8ce10000..0x8cff0000, the biggest one above the constant floor:
        // this title's image is 4 KB here, so the floor is its own image's end
        // and the answer comes from 0x8c070000..0x8ccd0000 -- 198 blocks
        // against 30, and against the single block Jet Set Radio's finished map
        // leaves above 0x8ce00000.
        assert_eq!(
            base_for_low_preset(&set, &boot, 0x0c01_0000, Some(&map)),
            Some(0x8c69_0000)
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn jet_set_radios_finished_map_leaves_only_one_block_up_high() {
        // The row as it stands after several sessions: 0x8ccd0000..0x8cfdffff
        // and 0x8cff0000 are all disc-read destinations, so the whole
        // relocatable window is taken bar block 254 -- 64 KB for a 56 KB
        // loader, with the title's own data hard against both sides. Below the
        // constant floor, 12.4 MB of RAM no read has ever landed in.
        const JSR_FULL: &str =
            "40000000000000000000000000000000000000000000000000e0ffffffffffbf";
        let map = memmap::MemoryMap::from_hex(JSR_FULL).unwrap();
        assert!(!map.is_marked(254), "0x8cfe0000 is the one block left up high");
        assert!(map.is_marked(253) && map.is_marked(255), "on both sides of it");

        let dir = fake_loader_dir("dcload-jsr-full", &[loaders::ISOLDR_DEFAULT_ADDR]);
        let set = loaders::LoaderSet::discover(Some(dir.to_string_lossy().into_owned()));
        // 1ST_READ.BIN as the disc holds it: 341696 bytes at 0x8c010000.
        let boot = vec![0u8; 341_696];
        assert_eq!(
            base_for_low_preset(&set, &boot, 0x0c01_0000, Some(&map)),
            Some(0x8c6a_0000)
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_low_preset_with_nothing_learned_still_avoids_the_two_it_rules_out() {
        // No row for this game and a binary that names nothing: every base is
        // equally unproven, so the answer is the middle of the window -- but
        // 0x8ce00000, which is both isoldr's default and where a chainloaded
        // loader is sitting, is still excluded rather than kept by default.
        let dir = fake_loader_dir("dcload-lowpreset-blank", &[loaders::ISOLDR_DEFAULT_ADDR]);
        let set = loaders::LoaderSet::discover(Some(dir.to_string_lossy().into_owned()));
        let got = base_for_low_preset(&set, &vec![0u8; 0x1000], 0x0c01_0000, None);
        assert_eq!(got, Some(0x8c81_0000));
        assert!(!loaders::ruled_out_by_low_preset(got.unwrap()));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
