use std::{process::ExitCode};

use crate::io::DcIoUDP;

use clap::{Parser, Subcommand};
use clap_num::maybe_hex;

#[macro_use]
extern crate log;

mod cmds;
mod cd;
mod fs;
mod disc_formats;
mod dispatch;
mod io;
mod loaders;
mod presets;
mod types;
mod ui;

const PROTOCOL_VERSION_LEGACY: [u8; 3] = [0, 0, 0];
const PROTOCOL_VERSION_MODERN: [u8; 3] = [2, 0, 3];
// Keep this easy to toggle. 1024 => legacy mode, 1440 => modern mode.
const CHUNK_SIZE: usize = 1440;

pub(crate) fn protocol_version() -> [u8; 3] {
    if CHUNK_SIZE <= 1024 {
        PROTOCOL_VERSION_LEGACY
    } else {
        PROTOCOL_VERSION_MODERN
    }
}

// Simple program to greet a person
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// Verbosity level (-v, -vv)
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: Option<u8>,

    /// UDP port to connect to
    #[arg(short, long, default_value_t = 53535)]
    port: u16,

    /// Host to connect to
    #[arg(short = 'H', long, default_value = "", value_hint = clap::ValueHint::Hostname)]
    host: String,

    /// Address to execute code at
    #[arg(short, long, default_value_t = 0x0c010000, default_value = "0x0c010000", value_parser = maybe_hex::<u32>)]
    address: u32,

    /// Directory of per-base dcload ELFs (dcload-0x8cfe8000.elf, ...).
    /// Defaults to $DCLOAD_LOADER_DIR, else `loaders/` in this project's root
    /// -- the same place for a debug build, a release build and `cargo run`,
    /// and outside `target/` so `cargo clean` leaves it alone. A `loaders`
    /// directory next to the executable is still honoured, last.
    /// Build the set with `make -C target-src/dcload loaders`.
    #[arg(long, value_hint = clap::ValueHint::DirPath)]
    loader_dir: Option<String>,

    /// Per-game settings table (game-presets.tsv, generated by dcload-ip's
    /// scripts/make-preset-db.py from DreamShell's isoldr presets).
    /// Defaults to $DCLOAD_GAME_DB, else game-presets.tsv beside the loaders,
    /// else in this project's root -- outside `target/`, and the same file for
    /// a debug build and a release build.
    #[arg(long, value_hint = clap::ValueHint::FilePath)]
    game_db: Option<String>,

    /// Link the loader at this address instead of asking the database.
    /// `--loader-base 0x8c004000` pins the stock base; use it to check whether
    /// a relocation is what changed a title's behaviour.
    #[arg(long, value_parser = maybe_hex::<u32>)]
    loader_base: Option<u32>,

    /// Never chainload: run whatever loader is already on the console.
    #[arg(long)]
    no_relocate: bool,

    /// Poke a 32-bit word into RAM after the title is uploaded and just before
    /// it runs: `--patch 0x8c0c0d6c=0x0009000b` (that word is `rts; nop`, i.e.
    /// "make this routine do nothing"). Repeatable. The address may be given in
    /// either window. Same mechanism as DreamShell's per-game pa1/pv1 fields --
    /// and, when a title hangs before its first disc read, the only instrument
    /// left: nothing else on the console can be read back at that point.
    #[arg(long, value_parser = parse_patch)]
    patch: Vec<(u32, u32)>,

    /// Do not neutralise a title's GAPS-bridge probe.
    ///
    /// By default the host looks in the uploaded image for the signature a
    /// Katana title uses to find an expansion device, and blunts it, because a
    /// title that finds the Broadband Adapter switches it OFF -- see
    /// AGENTS.md 4.12. Pass this to leave the title exactly as shipped and let
    /// dcload's own recovery handle it.
    #[arg(long)]
    no_gaps_guard: bool,

    /// Place a "phone home" probe at ADDR that reports through dcload's own
    /// syscall trampoline: `--probe 0x8c110bec=37` makes the console log
    /// `Write(1, .., 37)` the moment that address is executed. ID is 1..127
    /// and only names the probe. Repeatable.
    ///
    /// Prefer this to a `trapa` patch once a title has started: a title takes
    /// over the exception vectors during its own start-up, and from then on
    /// "the probe fired" and "the probe was never reached" are the same dead
    /// console. This path belongs to the loader, needs no vector table, and
    /// says so in the log. The stub destroys 28 bytes at ADDR and parks there.
    #[arg(long, value_parser = parse_probe)]
    probe: Vec<(u32, u8, Option<u32>)>,

    /// Enter the title through its own IP.BIN bootstrap instead of jumping
    /// straight into 1ST_READ.BIN -- what isoldr does for every preset with
    /// `fastboot = 0`, which includes Sonic Adventure 2.
    ///
    /// Loads all sixteen IP.BIN sectors to 0x8c008000, applies isoldr's four
    /// `Load_IPBin()` patches, and executes 0x8c00e000 (its second bootstrap)
    /// rather than the upload address. Without this the host only ever placed
    /// the single header sector and entered the binary directly, so the code a
    /// real disc runs between the two never ran at all -- and SA2 is the one
    /// title measured reading structures out of that region.
    ///
    /// Needs the loader out of the way: at the stock base dcload's own image
    /// covers 0x8c008000, so this is refused there rather than shooting the
    /// loader mid-upload.
    #[arg(long)]
    boot_ipbin: bool,

    #[command(subcommand)]
    command: Commands,
}

/// `ADDR=N[:PEEK]` for `--probe`. N is 1..=127.
///
/// Without PEEK, N only names the probe and the reported buffer is the stub's
/// own literal pool -- "this address was executed" and nothing more.
///
/// With PEEK, the stub reports N bytes read FROM PEEK instead, so reaching the
/// site also exfiltrates memory: `--probe 0x8c0100f2=4:0x8c0000bc` says "when
/// the title gets here, show me the four bytes of the GD syscall vector". That
/// is the only way to look at the title's RAM at a chosen instant, because
/// dcload does not run again until a GD syscall and a probe stops the title
/// before one can happen.
fn parse_probe(s: &str) -> Result<(u32, u8, Option<u32>), String> {
    let (addr, rest) = s
        .split_once('=')
        .ok_or_else(|| format!("expected ADDR=N[:PEEK], got '{s}'"))?;
    let (n, peek) = match rest.split_once(':') {
        Some((n, p)) => (n, Some(p)),
        None => (rest, None),
    };
    let num = |t: &str| -> Result<u32, String> {
        let t = t.trim();
        let r = if let Some(h) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
            u32::from_str_radix(h, 16)
        } else {
            t.parse::<u32>()
        };
        r.map_err(|e| format!("'{t}': {e}"))
    };
    let addr = num(addr)?;
    let n = num(n)?;
    if n == 0 || n > 127 {
        return Err(format!("probe length/id must be 1..=127, got {n}"));
    }
    let peek = peek.map(num).transpose()?;
    Ok((addr, n as u8, peek))
}

/// `ADDR=VALUE`, both decimal or 0x-hex, for `--patch`.
fn parse_patch(s: &str) -> Result<(u32, u32), String> {
    let (addr, value) = s
        .split_once('=')
        .ok_or_else(|| format!("expected ADDR=VALUE, got `{s}`"))?;
    Ok((
        maybe_hex::<u32>(addr.trim())?,
        maybe_hex::<u32>(value.trim())?,
    ))
}

/// Work out which base the loader should be at for this disc, and say why.
///
/// Returns `None` when there is no reason to move: no disc, no database, no
/// match. The caller keeps the running loader in that case, which is the stock
/// 0x8c004000 and is what every title got before any of this existed.
fn wanted_loader_base(args: &Args, disc: Option<&String>) -> Option<u32> {
    if args.no_relocate {
        return None;
    }
    if let Some(base) = args.loader_base {
        info!("loader base 0x{base:08x} (from --loader-base)");
        return Some(base);
    }
    let disc = disc?;

    let identity = match dispatch::identify_disc(disc) {
        Ok(id) => id,
        Err(reason) => {
            // A warning, not a debug line, and it carries the reason. This is
            // the last point at which a bad `-d` path is cheap to notice: the
            // run continues, the title is uploaded, and every disc read it
            // makes afterwards fails.
            warn!("{reason}");
            warn!("cannot choose a loader base for this title; keeping the loader where it is");
            return None;
        }
    };
    info!(
        "disc: {} [{} {} {}] boot-sector md5 {}",
        identity.title, identity.product, identity.version, identity.region, identity.md5
    );

    let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
    let (db_path, db_searched) = game_db_path(args, &loaders);

    let db = match presets::PresetDb::load(&db_path) {
        Ok(db) => db,
        Err(e) => {
            warn!(
                "no game database at {} ({e}); every title will run at the loader's \
                 current address. Generate it with dcload-ip's scripts/make-preset-db.py \
                 and put game-presets.tsv in this project's root. Looked in: {}.",
                db_path.display(),
                db_searched
            );
            return None;
        }
    };
    debug!("game database: {} rows from {}", db.len(), db_path.display());

    let (preset, kind) = match db.lookup(&identity) {
        Some(found) => found,
        None => {
            info!(
                "'{}' is not in the game database; keeping the loader where it is \
                 (the stock base is 0x{:08x})",
                identity.title,
                loaders::DEFAULT_BASE
            );
            return None;
        }
    };
    // The whole row, once, for anyone reconstructing a session from the log.
    // `dma` and `fastboot` describe DreamShell's own storage device and menu
    // and mean nothing on a network transport; `async` is isoldr's sectors-per
    // -request, which dcload fixes at 8 (GD_EMU_ASYNC) at build time.
    debug!(
        "preset: memory={:08x} async={} dma={} irq={} cdda={:08x} heap={:08x} \
         low={} fastboot={} type={} mode={} altread={}",
        preset.memory, preset.emu_async, preset.dma, preset.irq, preset.cdda,
        preset.heap, preset.low, preset.fastboot, preset.bin_type,
        preset.boot_mode, preset.altread
    );

    match kind {
        presets::MatchKind::BootSectorMd5 => info!(
            "matched '{}' exactly (boot-sector md5): loader wants 0x{:08x}",
            preset.title, preset.memory
        ),
        presets::MatchKind::Title => {
            let ambiguity = db.title_ambiguity(&identity.title);
            if ambiguity > 1 {
                warn!(
                    "matched '{}' BY TITLE ONLY, and presets under that title disagree \
                     about the address ({} different values); using 0x{:08x}. Pin it with \
                     --loader-base if this dump misbehaves.",
                    preset.title, ambiguity, preset.memory
                );
            } else {
                info!(
                    "matched '{}' by title (this exact dump is not in the database): \
                     loader wants 0x{:08x}",
                    preset.title, preset.memory
                );
            }
        }
    }

    // Say what the preset asked for that this host does not do. When a title
    // misbehaves, "its preset wanted interrupt hooking and we dropped it" is
    // the first thing worth knowing, and it is invisible otherwise.
    for note in preset.unsupported() {
        warn!("'{}': not honoured -- {}", preset.title, note);
    }

    Some(preset.memory)
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Upload a binary and execute it immediately
    UExec {
        /// Path to file to upload and execute
        #[arg(value_hint = clap::ValueHint::FilePath)]
        file: String,

        /// Path to file to redirect the reads to
        #[arg(short, long, value_hint = clap::ValueHint::FilePath, conflicts_with = "mount")]
        disc: Option<String>,

        #[arg(short, long, value_hint = clap::ValueHint::DirPath)]
        mount: Option<String>,

        /// Enable console redirection
        #[arg(short, long)]
        console: bool,
    },
    /// Upload a binary
    Upload {
        /// Path to file to upload
        #[arg(value_hint = clap::ValueHint::FilePath)]
        file: String,
    },
    /// Reboot the console (only works when dcload is in control)
    Reboot {},
    /// Write known patterns to free RAM and read them straight back, across
    /// several sizes and misalignments. Uploads no title and starts nothing --
    /// it only answers "can a read-back off this console be believed at all".
    SelftestReadback {},
    /// Read a disc image and print what it is and which loader base it wants.
    ///
    /// Touches no network and needs no Dreamcast, which is the point: when a
    /// title misbehaves, this separates "the image is not what you think" from
    /// "the console did something odd" in one command.
    Identify {
        /// Disc image (.gdi / .cdi / .iso)
        #[arg(value_hint = clap::ValueHint::FilePath)]
        disc: String,
    },
}

/// `identify`: everything the loader-placement pass would work out, printed.
fn identify_only(args: &Args, disc: &str) -> ExitCode {
    let identity = match dispatch::identify_disc(disc) {
        Ok(id) => id,
        Err(reason) => {
            error!("{reason}");
            return ExitCode::FAILURE;
        }
    };
    println!("title    : {}", identity.title);
    println!("product  : {} {}", identity.product, identity.version);
    println!("region   : {}", identity.region);
    println!("boot md5 : {}", identity.md5);

    let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
    let (db_path, db_searched) = game_db_path(args, &loaders);
    match presets::PresetDb::load(&db_path) {
        Err(e) => println!(
            "preset   : no database at {} ({e})\n           looked in: {}",
            db_path.display(),
            db_searched
        ),
        Ok(db) => match db.lookup(&identity) {
            None => println!(
                "preset   : not in the database ({} rows); would stay at 0x{:08x}",
                db.len(),
                loaders::DEFAULT_BASE
            ),
            Some((p, kind)) => {
                let how = match kind {
                    presets::MatchKind::BootSectorMd5 => "exact (boot-sector md5)".to_string(),
                    presets::MatchKind::Title => {
                        let n = db.title_ambiguity(&identity.title);
                        if n > 1 {
                            format!("BY TITLE, ambiguous ({n} different addresses)")
                        } else {
                            "by title".to_string()
                        }
                    }
                };
                println!("preset   : '{}' -- {}", p.title, how);
                println!("memory   : 0x{:08x}", p.memory);
                println!(
                    "loader   : {}",
                    if let Some(reason) = loaders::known_unsupported(p.memory) {
                        format!("UNSUPPORTED base -- {reason}")
                    } else if loaders.has(p.memory) {
                        format!("{} present", loaders.path_for(p.memory).display())
                    } else {
                        format!(
                            "MISSING dcload-0x{:08x}.elf in {} (looked in: {})",
                            p.memory,
                            loaders.dir().display(),
                            loaders.searched()
                        )
                    }
                );
                for note in p.unsupported() {
                    println!("not done : {note}");
                }
            }
        },
    }
    ExitCode::SUCCESS
}

/// (the table to read, every path considered).
///
/// Resolved exactly like the loader set: beside the loaders, then in the
/// project root, and only then next to the executable -- so `cargo clean`
/// cannot take it and debug and release read the same file. The second half of
/// the pair exists because "no game database at X" names one path and leaves
/// the user guessing about the others.
fn game_db_path(args: &Args, loaders: &loaders::LoaderSet) -> (std::path::PathBuf, String) {
    let exe = std::env::current_exe().ok();
    let cwd = std::env::current_dir().ok();
    let candidates = loaders::game_db_candidates(
        args.game_db.clone(),
        std::env::var("DCLOAD_GAME_DB").ok(),
        loaders.dir(),
        exe.as_deref(),
        cwd.as_deref(),
        env!("CARGO_MANIFEST_DIR"),
    );
    let chosen = candidates
        .iter()
        .find(|p| p.is_file())
        .unwrap_or(&candidates[0])
        .clone();
    let searched = candidates
        .iter()
        .map(|p| p.display().to_string())
        .collect::<Vec<_>>()
        .join(", ");
    (chosen, searched)
}

fn main() -> Result<ExitCode, Box<dyn std::error::Error>> {
    let args = Args::parse();
    // Logging goes through the progress display (see `ui`), so that a log
    // record never lands on top of a bar that is being drawn.
    ui::init_logging(args.verbose);
    // Before the socket: this one never talks to a Dreamcast.
    if let Commands::Identify { ref disc } = args.command {
        return Ok(identify_only(&args, disc));
    }

    let legacy_mode = protocol_version()[0] < 2;
    let remote_port = if legacy_mode { 31313 } else { args.port };
    let local_port = if legacy_mode { Some(31313) } else { None };
    let mut udpsender = DcIoUDP::new(args.host.clone(), remote_port, local_port)?;
    let (version_text, mut running_base) = match dispatch::query_loader(&mut udpsender) {
        Err(err) => {
            error!("Failed to contact the client: {}", err);
            return Ok(ExitCode::FAILURE);
        }
        Ok(v) => v,
    };
    info!(
        "Successfully connected to dcload-ip on host {} using port {}",
        args.host, args.port
    );
    match running_base {
        Some(base) => info!("dcload-ip version: {} (loaded at 0x{:08x})", version_text, base),
        None => info!(
            "dcload-ip version: {} (does not report its load address; \
             this build cannot be relocated per game)",
            version_text
        ),
    }

    // Relocate BEFORE uploading the title. Any chainload replaces the whole
    // loader, so a title uploaded first would be uploaded into an image that is
    // about to be overwritten -- and the game's own RAM is zero-filled by the
    // loader that comes up.
    if let Commands::UExec { ref disc, .. } = args.command
        && let Some(want) = wanted_loader_base(&args, disc.as_ref())
    {
        match running_base {
            Some(base) => {
                let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
                running_base = Some(dispatch::ensure_loader_base(
                    &mut udpsender,
                    &loaders,
                    base,
                    want,
                ));
            }
            None => warn!(
                "this title wants the loader at 0x{want:08x}, but the loader on the \
                 console does not report where it is, so it cannot be moved safely. \
                 Rebuild dcload-ip and re-burn its boot image (or re-run the CD/CDI) \
                 to get a loader that does."
            ),
        }
    }

    let result: Result<ExitCode, Box<dyn std::error::Error>> = match args.command {
        Commands::UExec {
            file,
            disc,
            mount,
            console,
        } => {
            let uploaded = file.clone();
            match dispatch::upload(&mut udpsender, file, args.address, running_base) {
            Err(e) => Err(e),
            Ok((addr, _size)) => {
                // After the title, before EXEC: the region is clear of both.
                // `boot_ipbin` decides both how much of IP.BIN goes over and
                // where execution starts; if the load fails there is no
                // bootstrap in RAM, so fall back to entering the binary rather
                // than jumping into whatever was there before.
                let mut entry = addr;
                if let Some(ref d) = disc {
                    match dispatch::load_ip_bin(
                        &mut udpsender,
                        d,
                        running_base,
                        args.boot_ipbin,
                    ) {
                        Ok(true) if args.boot_ipbin => {
                            entry = dispatch::IP_BIN_BOOTSTRAP_2_EXEC;
                        }
                        Ok(false) if args.boot_ipbin => {
                            // Declined, not failed -- the loader is sitting on
                            // the region. Entering 0x8c00e000 now would jump
                            // into the loader's own image.
                            warn!(
                                "--boot-ipbin declined (see above); entering \
                                 0x{addr:08x} directly"
                            );
                        }
                        Ok(_) => {}
                        Err(e) => {
                            warn!("could not load IP.BIN: {e}");
                            if args.boot_ipbin {
                                warn!(
                                    "--boot-ipbin asked for, but IP.BIN is not in RAM; \
                                     entering 0x{addr:08x} directly instead"
                                );
                            }
                        }
                    }
                } else if args.boot_ipbin {
                    warn!("--boot-ipbin needs a disc image; entering 0x{addr:08x} directly");
                }
                // Before --patch, so an explicit patch still wins over it.
                if !args.no_gaps_guard {
                    let guard = dispatch::gaps_probe_patches(&uploaded, args.address);
                    if !guard.is_empty()
                        && let Err(e) = dispatch::apply_patches(&mut udpsender, &guard)
                    {
                        warn!("could not neutralise the GAPS probe: {e}");
                    }
                }
                // Last, so a patch always wins over the bytes it replaces --
                // whether they came from the title, from IP.BIN, or from both.
                if !args.patch.is_empty()
                    && let Err(e) = dispatch::apply_patches(&mut udpsender, &args.patch)
                {
                    warn!("could not apply patches: {e}");
                }
                if !args.probe.is_empty()
                    && let Err(e) =
                        dispatch::apply_probes(&mut udpsender, &args.probe, running_base)
                {
                    warn!("could not place probes: {e}");
                }
                info!("Upload complete, executing at 0x{:08x}", entry);
                match dispatch::execute(&mut udpsender, entry, console || disc.is_some() || mount.is_some(), disc.is_some()) {
                    Err(e) => Err(e),
                    Ok(_) => {
                        if disc.is_some() || mount.is_some() || console {
                            dispatch::receive_syscalls(&mut udpsender, disc, mount)?;
                            return Ok(ExitCode::SUCCESS);
                        }
                        Ok(ExitCode::SUCCESS)
                    }
                }
            }
        }},
        Commands::Upload { file } => {
            return match dispatch::upload(&mut udpsender, file, args.address, running_base)
                .map(|_s| ExitCode::SUCCESS)
            {
                Err(e) => Err(e),
                Ok(code) => {
                    info!("Upload complete");
                    Ok(code)
                }
            };
        }
        // Handled before the socket is opened; unreachable here, but spelled
        // out rather than caught by a wildcard so adding a subcommand keeps
        // failing to compile until it is wired up.
        Commands::Identify { .. } => unreachable!("handled before connecting"),
        Commands::SelftestReadback {} => {
            return match dispatch::selftest_readback(&mut udpsender)? {
                true => Ok(ExitCode::SUCCESS),
                false => Ok(ExitCode::FAILURE),
            };
        }
        Commands::Reboot {} => {
            info!("Sending reboot command");
            dispatch::reboot(&mut udpsender)?;
            info!("Reboot command sent");
            return Ok(ExitCode::SUCCESS);
        } // _ => Err(Box::new(NotImplemented {
          //     feature: "Unknown command".to_string(),
          // })),
    };
    if let Err(returned_error) = result {
        error!("{}", returned_error);
        Ok(ExitCode::FAILURE)
    } else {
        Ok(ExitCode::SUCCESS)
    }
}
