use std::{process::ExitCode};

use crate::io::DcIoUDP;

use clap::{Parser, Subcommand};
use clap_num::maybe_hex;

#[macro_use]
extern crate log;

mod cmds;
mod cd;
mod fs;
mod disc_formats;
mod dispatch;
mod io;
mod loaders;
mod presets;
mod types;
mod ui;

const PROTOCOL_VERSION_LEGACY: [u8; 3] = [0, 0, 0];
const PROTOCOL_VERSION_MODERN: [u8; 3] = [2, 0, 3];
// Keep this easy to toggle. 1024 => legacy mode, 1440 => modern mode.
const CHUNK_SIZE: usize = 1440;

pub(crate) fn protocol_version() -> [u8; 3] {
    if CHUNK_SIZE <= 1024 {
        PROTOCOL_VERSION_LEGACY
    } else {
        PROTOCOL_VERSION_MODERN
    }
}

// Simple program to greet a person
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// Verbosity level (-v, -vv)
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: Option<u8>,

    /// UDP port to connect to
    #[arg(short, long, default_value_t = 53535)]
    port: u16,

    /// Host to connect to
    #[arg(short = 'H', long, default_value = "", value_hint = clap::ValueHint::Hostname)]
    host: String,

    /// Address to execute code at
    #[arg(short, long, default_value_t = 0x0c010000, default_value = "0x0c010000", value_parser = maybe_hex::<u32>)]
    address: u32,

    /// Directory of per-base dcload ELFs (dcload-0x8cfe8000.elf, ...).
    /// Defaults to $DCLOAD_LOADER_DIR, else `loaders/` in this project's root
    /// -- the same place for a debug build, a release build and `cargo run`,
    /// and outside `target/` so `cargo clean` leaves it alone. A `loaders`
    /// directory next to the executable is still honoured, last.
    /// Build the set with `make -C target-src/dcload loaders`.
    #[arg(long, value_hint = clap::ValueHint::DirPath)]
    loader_dir: Option<String>,

    /// Per-game settings table (game-presets.tsv, generated by dcload-ip's
    /// scripts/make-preset-db.py from DreamShell's isoldr presets).
    /// Defaults to $DCLOAD_GAME_DB, else game-presets.tsv beside the loaders,
    /// else in this project's root -- outside `target/`, and the same file for
    /// a debug build and a release build.
    #[arg(long, value_hint = clap::ValueHint::FilePath)]
    game_db: Option<String>,

    /// Link the loader at this address instead of asking the database.
    /// `--loader-base 0x8c004000` pins the stock base; use it to check whether
    /// a relocation is what changed a title's behaviour.
    #[arg(long, value_parser = maybe_hex::<u32>)]
    loader_base: Option<u32>,

    /// Never chainload: run whatever loader is already on the console.
    #[arg(long)]
    no_relocate: bool,

    /// Poke a 32-bit word into RAM after the title is uploaded and just before
    /// it runs: `--patch 0x8c0c0d6c=0x0009000b` (that word is `rts; nop`, i.e.
    /// "make this routine do nothing"). Repeatable. The address may be given in
    /// either window. Same mechanism as DreamShell's per-game pa1/pv1 fields --
    /// and, when a title hangs before its first disc read, the only instrument
    /// left: nothing else on the console can be read back at that point.
    #[arg(long, value_parser = parse_patch)]
    patch: Vec<(u32, u32)>,

    /// Do not neutralise a title's GAPS-bridge probe.
    ///
    /// By default the host looks in the uploaded image for the signature a
    /// Katana title uses to find an expansion device, and blunts it, because a
    /// title that finds the Broadband Adapter switches it OFF -- see
    /// AGENTS.md 4.12. Pass this to leave the title exactly as shipped and let
    /// dcload's own recovery handle it.
    #[arg(long)]
    no_gaps_guard: bool,

    /// Place a "phone home" probe at ADDR that reports through dcload's own
    /// syscall trampoline: `--probe 0x8c110bec=37` makes the console log
    /// `Write(1, .., 37)` the moment that address is executed. ID is 1..127
    /// and only names the probe. Repeatable.
    ///
    /// Prefer this to a `trapa` patch once a title has started: a title takes
    /// over the exception vectors during its own start-up, and from then on
    /// "the probe fired" and "the probe was never reached" are the same dead
    /// console. This path belongs to the loader, needs no vector table, and
    /// says so in the log. The stub destroys 28 bytes at ADDR and parks there.
    #[arg(long, value_parser = parse_probe)]
    probe: Vec<(u32, u8, Option<u32>)>,

    /// What to do about a SCRAMBLED boot binary.
    ///
    /// A binary meant to boot from a CD-R is stored with its 32-byte slices
    /// permuted, and the disc's own bootstrap unpermutes it while loading. This
    /// host never runs that bootstrap -- it enters the binary directly, as
    /// isoldr does -- so a scrambled one has to be undone here or what runs is
    /// noise. A `.gdi` dumped from a GD-ROM is never scrambled; a `.cdi`
    /// self-boot conversion usually is.
    ///
    /// `auto` (the default) undoes it only when it can be PROVEN, which is
    /// possible for homebrew and not for retail titles -- see
    /// `disc_formats::scramble`. If a title uploads cleanly and then does
    /// absolutely nothing, `--descramble always` is the next thing to try.
    #[arg(long, value_enum, default_value_t = DescrambleArg::Auto)]
    descramble: DescrambleArg,

    /// Enter the title through its own IP.BIN bootstrap instead of jumping
    /// straight into 1ST_READ.BIN -- what isoldr does for every preset with
    /// `fastboot = 0`, which includes Sonic Adventure 2.
    ///
    /// Loads all sixteen IP.BIN sectors to 0x8c008000, applies isoldr's four
    /// `Load_IPBin()` patches, and executes 0x8c00e000 (its second bootstrap)
    /// rather than the upload address. Without this the host only ever placed
    /// the single header sector and entered the binary directly, so the code a
    /// real disc runs between the two never ran at all -- and SA2 is the one
    /// title measured reading structures out of that region.
    ///
    /// Needs the loader out of the way: at the stock base dcload's own image
    /// covers 0x8c008000, so this is refused there rather than shooting the
    /// loader mid-upload.
    #[arg(long)]
    boot_ipbin: bool,

    #[command(subcommand)]
    command: Commands,
}

#[derive(clap::ValueEnum, Clone, Copy, Debug, Default, PartialEq, Eq)]
enum DescrambleArg {
    #[default]
    Auto,
    Always,
    Never,
}

impl From<DescrambleArg> for disc_formats::boot::Descramble {
    fn from(a: DescrambleArg) -> Self {
        match a {
            DescrambleArg::Auto => Self::Auto,
            DescrambleArg::Always => Self::Always,
            DescrambleArg::Never => Self::Never,
        }
    }
}

/// The bytes to upload, and what to call them in the log and on the bar.
///
/// POINT AT THE IMAGE, NOT AT A FILE YOU EXTRACTED FROM IT. A disc already says
/// which file it boots (IP.BIN names it) and where that file is, so extracting
/// `1ST_READ.BIN` by hand and then passing two paths that have to agree is work
/// nobody needs to do -- and one of the two being stale is a whole debugging
/// session.
/// `opened` is the image already open for the syscall loop, when the thing
/// being run IS that image -- which is the usual case, and re-opening it here
/// would re-read the zip directory and re-probe every track for nothing.
fn resolve_payload(
    args: &Args,
    file: &str,
    opened: Option<&dyn disc_formats::types::DiscFormat>,
) -> Result<(Vec<u8>, String), String> {
    let boot = match opened {
        Some(disc) => Some(
            disc_formats::boot::extract(disc, args.descramble.into())
                .map_err(|e| format!("{file}: {e}"))?,
        ),
        None if dispatch::is_disc_image(file) => {
            Some(dispatch::boot_binary(file, args.descramble.into())?)
        }
        None => None,
    };
    if let Some(boot) = boot {
        info!(
            "{file}: booting {} ({} bytes, LBA {})",
            boot.name,
            indicatif::HumanBytes(boot.bytes.len() as u64),
            boot.lba
        );
        return Ok((boot.bytes, boot.name));
    }
    dispatch::payload_from_file(std::path::Path::new(file)).map_err(|e| format!("{file}: {e}"))
}

/// Which image serves the title's disc reads.
///
/// When the thing being run IS a disc image, it is also the disc -- that is the
/// whole point of pointing at it. An explicit `-d` still wins, and `-m` (host
/// filesystem instead of a disc) turns it off.
fn effective_disc(file: &str, disc: &Option<String>, mount: &Option<String>) -> Option<String> {
    if disc.is_some() {
        return disc.clone();
    }
    if mount.is_some() {
        return None;
    }
    dispatch::is_disc_image(file).then(|| file.to_string())
}

/// `ADDR=N[:PEEK]` for `--probe`. N is 1..=127.
///
/// Without PEEK, N only names the probe and the reported buffer is the stub's
/// own literal pool -- "this address was executed" and nothing more.
///
/// With PEEK, the stub reports N bytes read FROM PEEK instead, so reaching the
/// site also exfiltrates memory: `--probe 0x8c0100f2=4:0x8c0000bc` says "when
/// the title gets here, show me the four bytes of the GD syscall vector". That
/// is the only way to look at the title's RAM at a chosen instant, because
/// dcload does not run again until a GD syscall and a probe stops the title
/// before one can happen.
fn parse_probe(s: &str) -> Result<(u32, u8, Option<u32>), String> {
    let (addr, rest) = s
        .split_once('=')
        .ok_or_else(|| format!("expected ADDR=N[:PEEK], got '{s}'"))?;
    let (n, peek) = match rest.split_once(':') {
        Some((n, p)) => (n, Some(p)),
        None => (rest, None),
    };
    let num = |t: &str| -> Result<u32, String> {
        let t = t.trim();
        let r = if let Some(h) = t.strip_prefix("0x").or_else(|| t.strip_prefix("0X")) {
            u32::from_str_radix(h, 16)
        } else {
            t.parse::<u32>()
        };
        r.map_err(|e| format!("'{t}': {e}"))
    };
    let addr = num(addr)?;
    let n = num(n)?;
    if n == 0 || n > 127 {
        return Err(format!("probe length/id must be 1..=127, got {n}"));
    }
    let peek = peek.map(num).transpose()?;
    Ok((addr, n as u8, peek))
}

/// `ADDR=VALUE`, both decimal or 0x-hex, for `--patch`.
fn parse_patch(s: &str) -> Result<(u32, u32), String> {
    let (addr, value) = s
        .split_once('=')
        .ok_or_else(|| format!("expected ADDR=VALUE, got `{s}`"))?;
    Ok((
        maybe_hex::<u32>(addr.trim())?,
        maybe_hex::<u32>(value.trim())?,
    ))
}

/// Work out which base the loader should be at for this disc, and say why.
///
/// Returns `None` when there is no reason to move: no disc, no database, no
/// match. The caller keeps the running loader in that case, which is the stock
/// 0x8c004000 and is what every title got before any of this existed.
fn wanted_loader_base(
    args: &Args,
    disc: Option<(&dyn disc_formats::types::DiscFormat, &str)>,
) -> Option<u32> {
    if args.no_relocate {
        return None;
    }
    if let Some(base) = args.loader_base {
        info!("loader base 0x{base:08x} (from --loader-base)");
        return Some(base);
    }
    let (disc, disc_path) = disc?;

    let identity = match dispatch::identify(disc, disc_path) {
        Ok(id) => id,
        Err(reason) => {
            // A warning, not a debug line, and it carries the reason. This is
            // the last point at which a bad `-d` path is cheap to notice: the
            // run continues, the title is uploaded, and every disc read it
            // makes afterwards fails.
            warn!("{reason}");
            warn!("cannot choose a loader base for this title; keeping the loader where it is");
            return None;
        }
    };
    info!(
        "disc: {} [{} {} {}] boot-sector md5 {}",
        identity.title, identity.product, identity.version, identity.region, identity.md5
    );

    let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
    let (db_path, db_searched) = game_db_path(args, &loaders);

    let db = match presets::PresetDb::load(&db_path) {
        Ok(db) => db,
        Err(e) => {
            warn!(
                "no game database at {} ({e}); every title will run at the loader's \
                 current address. Generate it with dcload-ip's scripts/make-preset-db.py \
                 and put game-presets.tsv in this project's root. Looked in: {}.",
                db_path.display(),
                db_searched
            );
            return None;
        }
    };
    debug!("game database: {} rows from {}", db.len(), db_path.display());

    let (preset, kind) = match db.lookup(&identity) {
        Some(found) => found,
        None => {
            info!(
                "'{}' is not in the game database; keeping the loader where it is \
                 (the stock base is 0x{:08x})",
                identity.title,
                loaders::DEFAULT_BASE
            );
            return None;
        }
    };
    // The whole row, once, for anyone reconstructing a session from the log.
    // `dma` and `fastboot` describe DreamShell's own storage device and menu
    // and mean nothing on a network transport; `async` is isoldr's sectors-per
    // -request, which dcload fixes at 8 (GD_EMU_ASYNC) at build time.
    debug!(
        "preset: memory={:08x} async={} dma={} irq={} cdda={:08x} heap={:08x} \
         low={} fastboot={} type={} mode={} altread={}",
        preset.memory, preset.emu_async, preset.dma, preset.irq, preset.cdda,
        preset.heap, preset.low, preset.fastboot, preset.bin_type,
        preset.boot_mode, preset.altread
    );

    match kind {
        presets::MatchKind::BootSectorMd5 => info!(
            "matched '{}' exactly (boot-sector md5): loader wants 0x{:08x}",
            preset.title, preset.memory
        ),
        presets::MatchKind::Title => {
            let ambiguity = db.title_ambiguity(&identity.title);
            if ambiguity > 1 {
                warn!(
                    "matched '{}' BY TITLE ONLY, and presets under that title disagree \
                     about the address ({} different values); using 0x{:08x}. Pin it with \
                     --loader-base if this dump misbehaves.",
                    preset.title, ambiguity, preset.memory
                );
            } else {
                info!(
                    "matched '{}' by title (this exact dump is not in the database): \
                     loader wants 0x{:08x}",
                    preset.title, preset.memory
                );
            }
        }
    }

    // Say what the preset asked for that this host does not do. When a title
    // misbehaves, "its preset wanted interrupt hooking and we dropped it" is
    // the first thing worth knowing, and it is invisible otherwise.
    for note in preset.unsupported() {
        warn!("'{}': not honoured -- {}", preset.title, note);
    }

    Some(preset.memory)
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Upload a binary and execute it immediately
    UExec {
        /// What to run: a binary (1ST_READ.BIN, an ELF), or a DISC IMAGE.
        ///
        /// Given an image (.gdi / .cdi / .iso, or a .zip holding one), the boot
        /// binary is read out of it and the same image serves the title's disc
        /// reads -- no extracting anything, and no second path to keep in step.
        #[arg(value_hint = clap::ValueHint::FilePath)]
        file: String,

        /// Path to file to redirect the reads to
        #[arg(short, long, value_hint = clap::ValueHint::FilePath, conflicts_with = "mount")]
        disc: Option<String>,

        #[arg(short, long, value_hint = clap::ValueHint::DirPath)]
        mount: Option<String>,

        /// Enable console redirection
        #[arg(short, long)]
        console: bool,
    },
    /// Upload a binary
    Upload {
        /// Path to file to upload. A disc image works here too: its boot binary
        /// is what gets uploaded.
        #[arg(value_hint = clap::ValueHint::FilePath)]
        file: String,
    },
    /// Write a disc image's boot binary out to a file.
    ///
    /// Touches no network. Mostly a way to check what `uexec <image>` is going
    /// to send before sending it -- and the only offline test there is that a
    /// zipped image reads back byte for byte like the loose one.
    Extract {
        /// Disc image (.gdi / .cdi / .iso / .zip)
        #[arg(value_hint = clap::ValueHint::FilePath)]
        disc: String,

        /// Where to write it. Default: the name the disc gives it, in the
        /// current directory.
        #[arg(short, long, value_hint = clap::ValueHint::FilePath)]
        output: Option<String>,
    },
    /// Reboot the console (only works when dcload is in control)
    Reboot {},
    /// Write known patterns to free RAM and read them straight back, across
    /// several sizes and misalignments. Uploads no title and starts nothing --
    /// it only answers "can a read-back off this console be believed at all".
    SelftestReadback {},
    /// Read a disc image and print what it is and which loader base it wants.
    ///
    /// Touches no network and needs no Dreamcast, which is the point: when a
    /// title misbehaves, this separates "the image is not what you think" from
    /// "the console did something odd" in one command.
    Identify {
        /// Disc image (.gdi / .cdi / .iso, or a .zip holding one -- add
        /// `#member` to pick one out of an archive with several)
        #[arg(value_hint = clap::ValueHint::FilePath)]
        disc: String,
    },
}

/// `identify`: everything the loader-placement pass would work out, printed.
fn identify_only(args: &Args, disc: &str) -> ExitCode {
    let reader = match dispatch::open_disc(disc) {
        Ok(d) => d,
        Err(reason) => {
            error!("{reason}");
            return ExitCode::FAILURE;
        }
    };
    let identity = match dispatch::identify(reader.as_ref(), disc) {
        Ok(id) => id,
        Err(reason) => {
            error!("{reason}");
            return ExitCode::FAILURE;
        }
    };
    println!("title    : {}", identity.title);
    println!("product  : {} {}", identity.product, identity.version);
    println!("region   : {}", identity.region);
    println!("boot md5 : {}", identity.md5);
    match disc_formats::boot::extract(reader.as_ref(), args.descramble.into()) {
        Ok(b) => {
            println!(
                "boot bin : {} ({} bytes at LBA {}){}",
                b.name,
                b.bytes.len(),
                b.lba,
                match (b.scrambling, b.descrambled) {
                    (_, true) => " -- unscrambled",
                    (disc_formats::scramble::Scrambling::Plain, _) => " -- plain",
                    _ => "",
                }
            );
            println!("bin md5  : {:x}", md5::compute(&b.bytes));
        }
        Err(e) => println!("boot bin : NOT FOUND -- {e}"),
    }

    let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
    let (db_path, db_searched) = game_db_path(args, &loaders);
    match presets::PresetDb::load(&db_path) {
        Err(e) => println!(
            "preset   : no database at {} ({e})\n           looked in: {}",
            db_path.display(),
            db_searched
        ),
        Ok(db) => match db.lookup(&identity) {
            None => println!(
                "preset   : not in the database ({} rows); would stay at 0x{:08x}",
                db.len(),
                loaders::DEFAULT_BASE
            ),
            Some((p, kind)) => {
                let how = match kind {
                    presets::MatchKind::BootSectorMd5 => "exact (boot-sector md5)".to_string(),
                    presets::MatchKind::Title => {
                        let n = db.title_ambiguity(&identity.title);
                        if n > 1 {
                            format!("BY TITLE, ambiguous ({n} different addresses)")
                        } else {
                            "by title".to_string()
                        }
                    }
                };
                println!("preset   : '{}' -- {}", p.title, how);
                println!("memory   : 0x{:08x}", p.memory);
                println!(
                    "loader   : {}",
                    if let Some(reason) = loaders::known_unsupported(p.memory) {
                        format!("UNSUPPORTED base -- {reason}")
                    } else if loaders.has(p.memory) {
                        format!("{} present", loaders.path_for(p.memory).display())
                    } else {
                        format!(
                            "MISSING dcload-0x{:08x}.elf in {} (looked in: {})",
                            p.memory,
                            loaders.dir().display(),
                            loaders.searched()
                        )
                    }
                );
                for note in p.unsupported() {
                    println!("not done : {note}");
                }
            }
        },
    }
    ExitCode::SUCCESS
}

/// A filename taken out of a disc image, made safe to use as a host path.
///
/// The bytes at IP.BIN +0x60 are whatever was mastered there: `iso9660::
/// boot_file_name` stops at a NUL or a space and passes everything else
/// through, separators and `..` included. Only the last component survives
/// here, and only its plain-filename characters; anything else becomes `_`,
/// and a name that is left empty or is `.`/`..` falls back to the usual one.
fn safe_output_name(name: &str) -> String {
    let base = name.rsplit(['/', '\\', ':']).next().unwrap_or(name);
    let cleaned: String = base
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-') {
                c
            } else {
                '_'
            }
        })
        .collect();
    // A leading dot is the last thing left that the image gets to decide and
    // the user does not see: `.bashrc` lands in the working directory and does
    // not show up in an `ls`. No boot binary is named that way.
    let cleaned = cleaned.trim_start_matches('.');
    if cleaned.trim_matches('.').is_empty() {
        return "1ST_READ.BIN".to_string();
    }
    cleaned.to_string()
}

/// `extract`: the boot binary out of an image and onto disk.
fn extract_only(args: &Args, disc: &str, output: Option<&str>) -> ExitCode {
    let boot = match dispatch::boot_binary(disc, args.descramble.into()) {
        Ok(b) => b,
        Err(e) => {
            error!("{e}");
            return ExitCode::FAILURE;
        }
    };
    // `-o` is a path the USER typed and is taken as it lies. The default is
    // not: it comes out of IP.BIN's sixteen-byte filename field, byte for
    // byte, and nothing in the image stops that field reading `../../.bashrc`.
    // Writing it verbatim would let the image choose where the host writes.
    let default = safe_output_name(&boot.name);
    let out = output.unwrap_or(&default);
    if let Err(e) = std::fs::write(out, &boot.bytes) {
        error!("cannot write {out}: {e}");
        return ExitCode::FAILURE;
    }
    info!(
        "{} -> {out} ({} bytes, md5 {:x}){}",
        boot.name,
        boot.bytes.len(),
        md5::compute(&boot.bytes),
        if boot.descrambled { ", unscrambled" } else { "" }
    );
    ExitCode::SUCCESS
}

/// (the table to read, every path considered).
///
/// Resolved exactly like the loader set: beside the loaders, then in the
/// project root, and only then next to the executable -- so `cargo clean`
/// cannot take it and debug and release read the same file. The second half of
/// the pair exists because "no game database at X" names one path and leaves
/// the user guessing about the others.
fn game_db_path(args: &Args, loaders: &loaders::LoaderSet) -> (std::path::PathBuf, String) {
    let exe = std::env::current_exe().ok();
    let cwd = std::env::current_dir().ok();
    let candidates = loaders::game_db_candidates(
        args.game_db.clone(),
        std::env::var("DCLOAD_GAME_DB").ok(),
        loaders.dir(),
        exe.as_deref(),
        cwd.as_deref(),
        env!("CARGO_MANIFEST_DIR"),
    );
    let chosen = candidates
        .iter()
        .find(|p| p.is_file())
        .unwrap_or(&candidates[0])
        .clone();
    let searched = candidates
        .iter()
        .map(|p| p.display().to_string())
        .collect::<Vec<_>>()
        .join(", ");
    (chosen, searched)
}

fn main() -> Result<ExitCode, Box<dyn std::error::Error>> {
    let args = Args::parse();
    // Logging goes through the progress display (see `ui`), so that a log
    // record never lands on top of a bar that is being drawn.
    ui::init_logging(args.verbose);
    // Before the socket: these never talk to a Dreamcast.
    if let Commands::Identify { ref disc } = args.command {
        return Ok(identify_only(&args, disc));
    }
    if let Commands::Extract {
        ref disc,
        ref output,
    } = args.command
    {
        return Ok(extract_only(&args, disc, output.as_deref()));
    }

    let legacy_mode = protocol_version()[0] < 2;
    let remote_port = if legacy_mode { 31313 } else { args.port };
    let local_port = if legacy_mode { Some(31313) } else { None };
    let mut udpsender = DcIoUDP::new(args.host.clone(), remote_port, local_port)?;
    let (version_text, mut running_base) = match dispatch::query_loader(&mut udpsender) {
        Err(err) => {
            error!("Failed to contact the client: {}", err);
            return Ok(ExitCode::FAILURE);
        }
        Ok(v) => v,
    };
    info!(
        "Successfully connected to dcload-ip on host {} using port {}",
        args.host, args.port
    );
    match running_base {
        Some(base) => info!("dcload-ip version: {} (loaded at 0x{:08x})", version_text, base),
        None => info!(
            "dcload-ip version: {} (does not report its load address; \
             this build cannot be relocated per game)",
            version_text
        ),
    }

    // Which image answers the title's disc reads. Worked out once, here,
    // because it decides both where the loader goes and what the syscall loop
    // is handed -- and those two disagreeing is a session with the right game
    // running at the wrong address.
    let redirect_disc: Option<String> = match &args.command {
        Commands::UExec {
            file, disc, mount, ..
        } => effective_disc(file, disc, mount),
        _ => None,
    };

    // Opened ONCE, here, and handed to everything that needs it: the identity
    // pass, the boot binary, IP.BIN and the syscall loop. Each `open_disc`
    // re-reads a zip's central directory, re-probes every CDI track for a PVD
    // and re-opens every GDI track file -- only the deflate index survives
    // between opens -- so a run that opened per use paid for all of that four
    // times before the title started.
    //
    // A failure here is reported and is not fatal: the title is still uploaded
    // and started, exactly as before, and every disc read it makes then fails.
    let mut disc_reader: Option<Box<dyn disc_formats::types::DiscFormat>> = None;
    if let Some(path) = redirect_disc.as_deref() {
        match dispatch::open_disc(path) {
            Ok(disc) => disc_reader = Some(disc),
            Err(e) => {
                error!("CDFS redirection DISABLED: {e}");
                error!("the title will be started anyway, and every disc read it makes will fail");
            }
        }
    }

    // Relocate BEFORE uploading the title. Any chainload replaces the whole
    // loader, so a title uploaded first would be uploaded into an image that is
    // about to be overwritten -- and the game's own RAM is zero-filled by the
    // loader that comes up.
    if matches!(args.command, Commands::UExec { .. })
        && let Some(want) = wanted_loader_base(
            &args,
            disc_reader.as_deref().zip(redirect_disc.as_deref()),
        )
    {
        match running_base {
            Some(base) => {
                let loaders = loaders::LoaderSet::discover(args.loader_dir.clone());
                running_base = Some(dispatch::ensure_loader_base(
                    &mut udpsender,
                    &loaders,
                    base,
                    want,
                ));
            }
            None => warn!(
                "this title wants the loader at 0x{want:08x}, but the loader on the \
                 console does not report where it is, so it cannot be moved safely. \
                 Rebuild dcload-ip and re-burn its boot image (or re-run the CD/CDI) \
                 to get a loader that does."
            ),
        }
    }

    let result: Result<ExitCode, Box<dyn std::error::Error>> = match args.command {
        Commands::UExec {
            ref file,
            ref mount,
            console,
            ..
        } => {
            // A disc image resolves to the boot binary it names; anything else
            // is uploaded as it lies.
            // The same image, when `uexec <image>` was given without `-d`.
            let payload_disc = disc_reader
                .as_deref()
                .filter(|_| redirect_disc.as_deref() == Some(file.as_str()));
            let (payload, label) = match resolve_payload(&args, file, payload_disc) {
                Ok(p) => p,
                Err(e) => {
                    error!("{e}");
                    return Ok(ExitCode::FAILURE);
                }
            };
            let has_disc = redirect_disc.is_some();
            match dispatch::upload_bytes(
                &mut udpsender,
                &payload,
                &label,
                args.address,
                running_base,
            ) {
            Err(e) => Err(e),
            Ok((addr, _size)) => {
                // After the title, before EXEC: the region is clear of both.
                // `boot_ipbin` decides both how much of IP.BIN goes over and
                // where execution starts; if the load fails there is no
                // bootstrap in RAM, so fall back to entering the binary rather
                // than jumping into whatever was there before.
                let mut entry = addr;
                if let (Some(reader), Some(d)) = (disc_reader.as_deref(), redirect_disc.as_ref()) {
                    match dispatch::load_ip_bin(
                        &mut udpsender,
                        reader,
                        d,
                        running_base,
                        args.boot_ipbin,
                    ) {
                        Ok(true) if args.boot_ipbin => {
                            entry = dispatch::IP_BIN_BOOTSTRAP_2_EXEC;
                        }
                        Ok(false) if args.boot_ipbin => {
                            // Declined, not failed -- the loader is sitting on
                            // the region. Entering 0x8c00e000 now would jump
                            // into the loader's own image.
                            warn!(
                                "--boot-ipbin declined (see above); entering \
                                 0x{addr:08x} directly"
                            );
                        }
                        Ok(_) => {}
                        Err(e) => {
                            warn!("could not load IP.BIN: {e}");
                            if args.boot_ipbin {
                                warn!(
                                    "--boot-ipbin asked for, but IP.BIN is not in RAM; \
                                     entering 0x{addr:08x} directly instead"
                                );
                            }
                        }
                    }
                } else if args.boot_ipbin {
                    if has_disc {
                        warn!(
                            "--boot-ipbin asked for, but the disc image could not be \
                             opened (see above); entering 0x{addr:08x} directly"
                        );
                    } else {
                        warn!("--boot-ipbin needs a disc image; entering 0x{addr:08x} directly");
                    }
                }
                // Before --patch, so an explicit patch still wins over it.
                if !args.no_gaps_guard {
                    let guard = dispatch::gaps_probe_patches(&payload, args.address);
                    if !guard.is_empty()
                        && let Err(e) = dispatch::apply_patches(&mut udpsender, &guard)
                    {
                        warn!("could not neutralise the GAPS probe: {e}");
                    }
                }
                // Last, so a patch always wins over the bytes it replaces --
                // whether they came from the title, from IP.BIN, or from both.
                if !args.patch.is_empty()
                    && let Err(e) = dispatch::apply_patches(&mut udpsender, &args.patch)
                {
                    warn!("could not apply patches: {e}");
                }
                if !args.probe.is_empty()
                    && let Err(e) =
                        dispatch::apply_probes(&mut udpsender, &args.probe, running_base)
                {
                    warn!("could not place probes: {e}");
                }
                info!("Upload complete, executing at 0x{:08x}", entry);
                // The title is on the console now; the host's copy is only
                // holding up to 16 MiB for the length of the session.
                drop(payload);
                match dispatch::execute(&mut udpsender, entry, console || has_disc || mount.is_some(), has_disc) {
                    Err(e) => Err(e),
                    Ok(_) => {
                        if has_disc || mount.is_some() || console {
                            dispatch::receive_syscalls(&mut udpsender, disc_reader, mount.clone())?;
                            return Ok(ExitCode::SUCCESS);
                        }
                        Ok(ExitCode::SUCCESS)
                    }
                }
            }
        }},
        Commands::Upload { ref file } => {
            let (payload, label) = match resolve_payload(&args, file, None) {
                Ok(p) => p,
                Err(e) => {
                    error!("{e}");
                    return Ok(ExitCode::FAILURE);
                }
            };
            return match dispatch::upload_bytes(
                &mut udpsender,
                &payload,
                &label,
                args.address,
                running_base,
            )
            .map(|_s| ExitCode::SUCCESS)
            {
                Err(e) => Err(e),
                Ok(code) => {
                    info!("Upload complete");
                    Ok(code)
                }
            };
        }
        // Handled before the socket is opened; unreachable here, but spelled
        // out rather than caught by a wildcard so adding a subcommand keeps
        // failing to compile until it is wired up.
        Commands::Identify { .. } | Commands::Extract { .. } => {
            unreachable!("handled before connecting")
        }
        Commands::SelftestReadback {} => {
            return match dispatch::selftest_readback(&mut udpsender)? {
                true => Ok(ExitCode::SUCCESS),
                false => Ok(ExitCode::FAILURE),
            };
        }
        Commands::Reboot {} => {
            info!("Sending reboot command");
            dispatch::reboot(&mut udpsender)?;
            info!("Reboot command sent");
            return Ok(ExitCode::SUCCESS);
        } // _ => Err(Box::new(NotImplemented {
          //     feature: "Unknown command".to_string(),
          // })),
    };
    if let Err(returned_error) = result {
        error!("{}", returned_error);
        Ok(ExitCode::FAILURE)
    } else {
        Ok(ExitCode::SUCCESS)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The default output name comes out of the IMAGE, and nothing in an image
    /// stops those sixteen bytes reading `../../.bashrc`. `extract` would then
    /// write there, with no confirmation and no overwrite check.
    #[test]
    fn an_image_cannot_choose_where_extract_writes() {
        assert_eq!(safe_output_name("1ST_READ.BIN"), "1ST_READ.BIN");
        assert_eq!(safe_output_name("0WINCEOS.BIN"), "0WINCEOS.BIN");
        for hostile in ["../../.bashrc", "/etc/cron.d/x", r"..\..\.bashrc"] {
            let out = safe_output_name(hostile);
            assert!(!out.contains('/') && !out.contains('\\'), "{hostile} -> {out}");
            assert!(!out.starts_with('.'), "{hostile} -> {out}");
        }
        assert_eq!(safe_output_name(".."), "1ST_READ.BIN");
        assert_eq!(safe_output_name(""), "1ST_READ.BIN");
    }
}
